In [2]:
# 기본 import 및 DB URL 입력

import getpass
import os
from typing import Any

import pandas as pd
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import SQLAlchemyError

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 120)

# 권장: 환경변수로 DB URL 설정
# 예:
# PostgreSQL: postgresql+psycopg://USER:PASSWORD@HOST:5432/DB_NAME
#
# 환경변수명은 필요하면 바꿔도 됩니다.
DB_URL = os.getenv("RISK_DB_URL")

if not DB_URL:
    DB_URL = getpass.getpass(
        "DB URL을 입력하세요. 예: postgresql+psycopg://name:password@localhost:15432/smap\n"
    )

# schema가 있는 DB라면 입력합니다.
# PostgreSQL public schema라면 "public" 또는 None 모두 가능하지만, 우선 None으로 둡니다.
DB_SCHEMA = os.getenv("RISK_DB_SCHEMA") or None

print("DB URL 입력 여부:", bool(DB_URL))
print("DB_SCHEMA:", DB_SCHEMA)

DB URL 입력 여부: True
DB_SCHEMA: None

In [3]:
# DB 연결 확인

try:
    engine = create_engine(
        DB_URL,
        pool_pre_ping=True,
        future=True,
    )

    with engine.connect() as conn:
        result = conn.execute(text("SELECT 1 AS connection_ok"))
        row = result.mappings().one()

    print("DB 연결 성공")
    print("connection_ok:", row["connection_ok"])
    print("dialect:", engine.dialect.name)

except SQLAlchemyError as e:
    print("DB 연결 실패")
    print(type(e).__name__)
    print(e)
    raise

DB 연결 성공
connection_ok: 1
dialect: postgresql

In [4]:
# Cell 4. 필수 테이블 존재 확인

REQUIRED_TABLES_STEP_1 = [
    "ai_prediction_results",
]

inspector = inspect(engine)

available_tables = set(inspector.get_table_names(schema=DB_SCHEMA))
missing_tables = [t for t in REQUIRED_TABLES_STEP_1 if t not in available_tables]

print("테이블 수:", len(available_tables))
print("필수 테이블 확인 대상:", REQUIRED_TABLES_STEP_1)

if missing_tables:
    print("누락 테이블:", missing_tables)
    print("현재 조회 가능한 테이블 일부:")
    print(sorted(list(available_tables))[:50])
    raise RuntimeError(f"필수 테이블이 없습니다: {missing_tables}")

print("필수 테이블 확인 완료")

테이블 수: 26
필수 테이블 확인 대상: ['ai_prediction_results']
필수 테이블 확인 완료

In [5]:
# Cell 5. ai_prediction_results 컬럼 확인


def get_columns(table_name: str) -> list[str]:
    return [col["name"] for col in inspector.get_columns(table_name, schema=DB_SCHEMA)]


prediction_result_columns = get_columns("ai_prediction_results")

print("ai_prediction_results 컬럼 수:", len(prediction_result_columns))
prediction_result_columns

ai_prediction_results 컬럼 수: 16

['prediction_id',
 'order_id',
 'plan_id',
 'product_id',
 'line_id',
 'delay_probability',
 'risk_level',
 'predicted_delay_days',
 'cause_detail',
 'analysis_summary',
 'recommended_action',
 'model_name',
 'model_version',
 'is_notified',
 'is_checked',
 'predicted_at']

In [6]:
# Cell 5-1. 분석 대상 조회에 필요한 최소 컬럼 점검

MIN_REQUIRED_COLUMNS = [
    "prediction_id",
    "order_id",
    "risk_level",
    "delay_probability",
]

missing_columns = [col for col in MIN_REQUIRED_COLUMNS if col not in prediction_result_columns]

if missing_columns:
    print("누락 컬럼:", missing_columns)
    print("현재 ai_prediction_results 컬럼:")
    print(prediction_result_columns)
    raise RuntimeError(
        "분석 대상 조회에 필요한 최소 컬럼이 없습니다. "
        "실제 컬럼명을 알려주시면 쿼리를 맞춰드리겠습니다."
    )

print("최소 컬럼 확인 완료")

최소 컬럼 확인 완료

In [7]:
# Cell 6. 테이블 참조 함수

preparer = engine.dialect.identifier_preparer


def table_ref(table_name: str) -> str:
    if DB_SCHEMA:
        return f"{preparer.quote_schema(DB_SCHEMA)}.{preparer.quote(table_name)}"
    return preparer.quote(table_name)


AI_PREDICTION_RESULTS = table_ref("ai_prediction_results")

print("ai_prediction_results 참조명:", AI_PREDICTION_RESULTS)

ai_prediction_results 참조명: ai_prediction_results

In [8]:
# Cell 7. 테스트 대상 prediction_id 설정

# 특정 prediction_id를 알고 있다면 숫자로 입력하세요.
# 예: TARGET_PREDICTION_ID = 10001
TARGET_PREDICTION_ID: int | None = 13

SAFE_RISK_LEVEL = "SAFE"

print("TARGET_PREDICTION_ID:", TARGET_PREDICTION_ID)
print("SAFE_RISK_LEVEL:", SAFE_RISK_LEVEL)

TARGET_PREDICTION_ID: 13
SAFE_RISK_LEVEL: SAFE

In [9]:
# Cell 8. SAFE가 아닌 분석 대상 1건 조회


def choose_order_column(columns: list[str]) -> str:
    for candidate in ["predicted_at", "created_at", "updated_at", "prediction_id"]:
        if candidate in columns:
            return candidate
    return "prediction_id"


def build_unprocessed_condition(columns: list[str]) -> str:
    """
    상세 분석이 아직 작성되지 않은 예측 결과를 찾기 위한 조건.
    컬럼이 있는 경우에만 조건에 포함합니다.
    """
    candidate_cols = [
        "cause_detail",
        "analysis_summary",
        "recommended_action",
    ]
    existing = [col for col in candidate_cols if col in columns]

    if not existing:
        # 상세 분석 컬럼이 없으면 미분석 여부를 판별할 수 없으므로 조건을 걸지 않습니다.
        return "1 = 1"

    return "(" + " OR ".join([f"{preparer.quote(col)} IS NULL" for col in existing]) + ")"


order_col = choose_order_column(prediction_result_columns)
unprocessed_condition = build_unprocessed_condition(prediction_result_columns)

if TARGET_PREDICTION_ID is not None:
    sql = f"""
        SELECT *
        FROM {AI_PREDICTION_RESULTS}
        WHERE prediction_id = :prediction_id
        LIMIT 1
    """
    params = {"prediction_id": TARGET_PREDICTION_ID}
else:
    sql = f"""
        SELECT *
        FROM {AI_PREDICTION_RESULTS}
        WHERE risk_level <> :safe_risk_level
          AND {unprocessed_condition}
        ORDER BY {preparer.quote(order_col)} DESC
        LIMIT 1
    """
    params = {"safe_risk_level": SAFE_RISK_LEVEL}

with engine.connect() as conn:
    target_df = pd.read_sql(text(sql), conn, params=params)

print("조회 row 수:", len(target_df))

if target_df.empty:
    print("분석 대상이 없습니다.")
    print("- TARGET_PREDICTION_ID가 None이면 SAFE가 아닌 미분석 예측 결과가 없는 상태입니다.")
    print("- 특정 prediction_id가 있다면 TARGET_PREDICTION_ID에 넣고 다시 실행하세요.")
else:
    display(target_df)

조회 row 수: 1

,prediction_id,order_id,plan_id,product_id,line_id,delay_probability,risk_level,predicted_delay_days,cause_detail,analysis_summary,recommended_action,model_name,model_version,is_notified,is_checked,predicted_at
0,13,397,424,2,2,0.5385,WARNING,1.98,"복합 원인(자재 부족)이 납기 지연 위험에 영향을 주고 있습니다. 부족 또는 부분 예약 상태인 핵심 자재: Stabilizer, White Masterbatch.","생산계획 424 기준 ORD-202605-027의 납기 지연 확률은 0.5385, 위험 등급은 WARNING입니다. 주요 원인은 자재 부족이며, 예상 지연일은 약 1.98일입니다.","부족 자재와 입고 예정일을 확인하고, 자재 확보 전 생산계획은 후순위로 조정하십시오.",smap-delay-risk-baseline,v0.1.0,True,False,2026-06-01 00:00:00+00:00

In [10]:
# Cell 9. SAFE 여부와 Agent 실행 가능 여부 확인

if target_df.empty:
    agent_should_run = False
    target_prediction = None
else:
    target_prediction = target_df.iloc[0].to_dict()
    risk_level = str(target_prediction.get("risk_level"))

    agent_should_run = risk_level != SAFE_RISK_LEVEL

    print("선택된 prediction_id:", target_prediction.get("prediction_id"))
    print("order_id:", target_prediction.get("order_id"))
    print("plan_id:", target_prediction.get("plan_id"))
    print("delay_probability:", target_prediction.get("delay_probability"))
    print("risk_level:", risk_level)
    print("predicted_delay_days:", target_prediction.get("predicted_delay_days"))

    if agent_should_run:
        print("판정: SAFE가 아니므로 AI Risk Analysis Agent 실행 대상입니다.")
    else:
        print("판정: SAFE이므로 상세 원인 분석을 실행하지 않습니다.")

선택된 prediction_id: 13
order_id: 397
plan_id: 424
delay_probability: 0.5385
risk_level: WARNING
predicted_delay_days: 1.98
판정: SAFE가 아니므로 AI Risk Analysis Agent 실행 대상입니다.

In [11]:
# Cell 10. 다음 단계 입력 객체 구성

if not agent_should_run:
    agent_input = None
    print("Agent 입력 객체를 만들지 않았습니다.")
else:
    agent_input = {
        "prediction_id": target_prediction.get("prediction_id"),
        "order_id": target_prediction.get("order_id"),
        "plan_id": target_prediction.get("plan_id"),
        "delay_probability": target_prediction.get("delay_probability"),
        "risk_level": target_prediction.get("risk_level"),
        "predicted_delay_days": target_prediction.get("predicted_delay_days"),
    }

    print("Agent 입력 객체:", agent_input)

Agent 입력 객체: {'prediction_id': 13, 'order_id': 397, 'plan_id': 424, 'delay_probability': 0.5385, 'risk_level': 'WARNING', 'predicted_delay_days': 1.98}

In [12]:
# Cell 11. Context Load 대상 테이블 자동 매핑


# 이미 앞 단계에서 생성된 객체가 있어야 합니다.
# engine
# inspector
# DB_SCHEMA
# table_ref
# preparer
# agent_input

available_tables = set(inspector.get_table_names(schema=DB_SCHEMA))

TABLE_CANDIDATES = {
    "ai_prediction_results": ["ai_prediction_results"],
    "customer_orders": ["customer_orders"],
    "production_plans": ["production_plans"],
    "production_plan_materials": ["production_plan_materials"],
    "material_inventories": ["material_inventories"],
    "production_lines": ["production_lines"],
    "line_status": ["line_status", "line_statuses"],
    "production_machines": ["production_machines", "machines"],
    "machine_statuses": ["machine_statuses", "machine_status"],
    "production_results": ["production_results"],
    "products": ["products"],
    "materials": ["materials"],
}


def resolve_table(candidates: list[str]) -> str | None:
    for table_name in candidates:
        if table_name in available_tables:
            return table_name
    return None


TABLE_MAP: dict[str, str | None] = {
    logical_name: resolve_table(candidates) for logical_name, candidates in TABLE_CANDIDATES.items()
}

print("Context Load 테이블 매핑 결과")
for logical_name, actual_name in TABLE_MAP.items():
    status = "OK" if actual_name else "MISSING"
    print(f"{logical_name:28s} -> {actual_name} [{status}]")

Context Load 테이블 매핑 결과
ai_prediction_results        -> ai_prediction_results [OK]
customer_orders              -> customer_orders [OK]
production_plans             -> production_plans [OK]
production_plan_materials    -> production_plan_materials [OK]
material_inventories         -> material_inventories [OK]
production_lines             -> production_lines [OK]
line_status                  -> line_status [OK]
production_machines          -> production_machines [OK]
machine_statuses             -> machine_statuses [OK]
production_results           -> production_results [OK]
products                     -> products [OK]
materials                    -> materials [OK]

In [13]:
# Cell 12. 매핑된 테이블 컬럼 확인


def get_table_columns_if_exists(table_name: str | None) -> list[str]:
    if table_name is None:
        return []
    return [col["name"] for col in inspector.get_columns(table_name, schema=DB_SCHEMA)]


TABLE_COLUMNS: dict[str, list[str]] = {
    logical_name: get_table_columns_if_exists(actual_name)
    for logical_name, actual_name in TABLE_MAP.items()
}

for logical_name, cols in TABLE_COLUMNS.items():
    print("\n" + "=" * 80)
    print(f"[{logical_name}] actual_table={TABLE_MAP[logical_name]}")
    print(f"columns ({len(cols)}):")
    print(cols)

================================================================================
[ai_prediction_results] actual_table=ai_prediction_results
columns (16):
['prediction_id', 'order_id', 'plan_id', 'product_id', 'line_id', 'delay_probability', 'risk_level', 'predicted_delay_days', 'cause_detail', 'analysis_summary', 'recommended_action', 'model_name', 'model_version', 'is_notified', 'is_checked', 'predicted_at']

================================================================================
[customer_orders] actual_table=customer_orders
columns (13):
['order_id', 'order_no', 'product_id', 'order_quantity', 'customer_name', 'customer_contact_name', 'order_date', 'due_date', 'contract_amount', 'late_penalty_amount', 'order_status', 'created_at', 'updated_at']

================================================================================
[production_plans] actual_table=production_plans
columns (14):
['plan_id', 'order_id', 'product_id', 'line_id', 'operator_id', 'planned_start_at', 'planned_end_at', 'estimated_duration_hr', 'planned_quantity', 'plan_sequence', 'plan_status', 'created_at', 'updated_at', 'is_current']

================================================================================
[production_plan_materials] actual_table=production_plan_materials
columns (12):
['plan_material_id', 'plan_id', 'material_id', 'required_quantity', 'reserved_quantity', 'consumed_quantity', 'shortage_quantity', 'material_plan_status', 'created_at', 'updated_at', 'ever_had_material_shortage', 'inbound_delay_days']

================================================================================
[material_inventories] actual_table=material_inventories
columns (12):
['inventory_id', 'material_id', 'current_quantity', 'available_quantity', 'reserved_quantity', 'safety_stock_quantity', 'expected_inbound_at', 'expected_inbound_quantity', 'inventory_status', 'updated_at', 'version', 'created_at']

================================================================================
[production_lines] actual_table=production_lines
columns (9):
['line_id', 'line_code', 'line_name', 'max_capacity_per_day', 'capacity_unit', 'supports_changeover', 'is_active', 'description', 'updated_at']

================================================================================
[line_status] actual_table=line_status
columns (15):
['line_status_id', 'line_id', 'product_id', 'plan_id', 'operator_id', 'recorded_at', 'operation_status', 'throughput_rate', 'current_yield_rate', 'waiting_quantity', 'waiting_time_hr', 'processed_quantity', 'defect_quantity', 'utilization_rate', 'progress_rate']

================================================================================
[production_machines] actual_table=production_machines
columns (8):
['machine_id', 'line_id', 'machine_code', 'machine_name', 'machine_type', 'machine_role', 'machine_order', 'updated_at']

================================================================================
[machine_statuses] actual_table=machine_statuses
columns (11):
['machine_status_id', 'machine_id', 'line_id', 'plan_id', 'product_id', 'recorded_at', 'operation_status', 'processed_quantity', 'defect_quantity', 'status_note', 'updated_at']

================================================================================
[production_results] actual_table=production_results
columns (20):
['result_id', 'plan_id', 'order_id', 'product_id', 'line_id', 'planned_start_at', 'actual_start_at', 'planned_end_at', 'actual_end_at', 'planned_quantity', 'actual_quantity', 'defect_quantity', 'yield_rate', 'actual_duration_hr', 'actual_setup_time_hr', 'actual_delay_hr', 'is_delayed', 'actual_delay_reason', 'result_status', 'updated_at']

================================================================================
[products] actual_table=products
columns (9):
['product_id', 'product_code', 'product_name', 'product_category', 'unit', 'average_yield_rate', 'min_production_quantity', 'description', 'updated_at']

================================================================================
[materials] actual_table=materials
columns (7):
['material_id', 'material_code', 'material_name', 'material_type', 'unit', 'description', 'updated_at']

In [14]:
# Cell 13. 조회 Helper 함수 정의

import pandas as pd
from sqlalchemy import text


def q(col_name: str) -> str:
    """컬럼명 quote."""
    return preparer.quote(col_name)


def tref_by_key(logical_table_key: str) -> str:
    """logical table key를 실제 SQL 테이블 참조명으로 변환."""
    actual_table = TABLE_MAP.get(logical_table_key)
    if not actual_table:
        raise RuntimeError(f"테이블이 매핑되지 않았습니다: {logical_table_key}")
    return table_ref(actual_table)


def has_table(logical_table_key: str) -> bool:
    return TABLE_MAP.get(logical_table_key) is not None


def has_col(logical_table_key: str, col_name: str) -> bool:
    return col_name in TABLE_COLUMNS.get(logical_table_key, [])


def read_df(sql: str, params: dict | None = None) -> pd.DataFrame:
    with engine.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params or {})


def read_by_equal(
    logical_table_key: str,
    column_name: str,
    value,
    limit: int | None = None,
    order_by: str | None = None,
    descending: bool = True,
) -> pd.DataFrame:
    if not has_table(logical_table_key):
        return pd.DataFrame()

    if not has_col(logical_table_key, column_name):
        return pd.DataFrame()

    sql = f"""
        SELECT *
        FROM {tref_by_key(logical_table_key)}
        WHERE {q(column_name)} = :value
    """

    if order_by and has_col(logical_table_key, order_by):
        direction = "DESC" if descending else "ASC"
        sql += f"\nORDER BY {q(order_by)} {direction}"

    if limit:
        sql += f"\nLIMIT {limit}"

    return read_df(sql, {"value": value})


def read_by_in(
    logical_table_key: str,
    column_name: str,
    values: list,
    limit: int | None = None,
) -> pd.DataFrame:
    if not values:
        return pd.DataFrame()

    if not has_table(logical_table_key):
        return pd.DataFrame()

    if not has_col(logical_table_key, column_name):
        return pd.DataFrame()

    params = {f"v{i}": v for i, v in enumerate(values)}
    placeholders = ", ".join([f":v{i}" for i in range(len(values))])

    sql = f"""
        SELECT *
        FROM {tref_by_key(logical_table_key)}
        WHERE {q(column_name)} IN ({placeholders})
    """

    if limit:
        sql += f"\nLIMIT {limit}"

    return read_df(sql, params)


print("조회 Helper 준비 완료")

조회 Helper 준비 완료

In [15]:
# Cell 14. Prediction / Order / Plan 기본 데이터 조회

if agent_input is None:
    raise RuntimeError("agent_input이 없습니다. 1단계 Cell 10을 먼저 확인하세요.")

prediction_id = agent_input["prediction_id"]
order_id = agent_input["order_id"]
plan_id = agent_input["plan_id"]
product_id = agent_input.get("product_id")
line_id = agent_input.get("line_id")

# 1) prediction
prediction_df = read_by_equal(
    logical_table_key="ai_prediction_results",
    column_name="prediction_id",
    value=prediction_id,
    limit=1,
)

if prediction_df.empty:
    raise RuntimeError(f"prediction_id={prediction_id} 결과가 없습니다.")

prediction_row = prediction_df.iloc[0].to_dict()

# agent_input에 없는 product_id, line_id 보완
product_id = prediction_row.get("product_id")
line_id = prediction_row.get("line_id")

# 2) order
order_df = read_by_equal(
    logical_table_key="customer_orders",
    column_name="order_id",
    value=order_id,
    limit=1,
)

# 완료/취소 주문은 상세 리스크 분석 대상에서 제외합니다.
if not order_df.empty and "order_status" in order_df.columns:
    order_status = str(order_df.iloc[0].get("order_status")).upper()

    excluded_order_statuses = {
        "COMPLETED",
        "DELIVERED",
        "CANCELLED",
        "CANCELED",
        "SHIPPED",
    }

    if order_status in excluded_order_statuses:
        raise RuntimeError(
            f"현재 선택된 order_id={order_id}는 order_status={order_status}입니다. "
            "완료/납품/취소 주문은 리스크 상세 분석 대상이 아닙니다. "
            "TARGET_PREDICTION_ID를 미완료 위험 주문으로 변경하세요."
        )


# 3) plan
if plan_id is not None:
    plan_df = read_by_equal(
        logical_table_key="production_plans",
        column_name="plan_id",
        value=plan_id,
        limit=1,
    )
else:
    plan_df = pd.DataFrame()

# plan_id로 못 찾으면 order_id 기준으로 재조회
if plan_df.empty and has_col("production_plans", "order_id"):
    plan_df = read_by_equal(
        logical_table_key="production_plans",
        column_name="order_id",
        value=order_id,
        limit=10,
        order_by="planned_start_at" if has_col("production_plans", "planned_start_at") else None,
        descending=False,
    )

print("prediction_df:", prediction_df.shape)
print("order_df:", order_df.shape)
print("plan_df:", plan_df.shape)

display(prediction_df)
display(order_df)
display(plan_df)

prediction_df: (1, 16)
order_df: (1, 13)
plan_df: (1, 14)

,prediction_id,order_id,plan_id,product_id,line_id,delay_probability,risk_level,predicted_delay_days,cause_detail,analysis_summary,recommended_action,model_name,model_version,is_notified,is_checked,predicted_at
0,13,397,424,2,2,0.5385,WARNING,1.98,"복합 원인(자재 부족)이 납기 지연 위험에 영향을 주고 있습니다. 부족 또는 부분 예약 상태인 핵심 자재: Stabilizer, White Masterbatch.","생산계획 424 기준 ORD-202605-027의 납기 지연 확률은 0.5385, 위험 등급은 WARNING입니다. 주요 원인은 자재 부족이며, 예상 지연일은 약 1.98일입니다.","부족 자재와 입고 예정일을 확인하고, 자재 확보 전 생산계획은 후순위로 조정하십시오.",smap-delay-risk-baseline,v0.1.0,True,False,2026-06-01 00:00:00+00:00

,order_id,order_no,product_id,order_quantity,customer_name,customer_contact_name,order_date,due_date,contract_amount,late_penalty_amount,order_status,created_at,updated_at
0,397,ORD-202605-027,2,12800,H케미칼,한지우,2026-05-23,2026-06-21,33262380.0,1970292.0,IN_PROGRESS,2026-05-23 00:00:00+00:00,2026-05-23 00:00:00+00:00

,plan_id,order_id,product_id,line_id,operator_id,planned_start_at,planned_end_at,estimated_duration_hr,planned_quantity,plan_sequence,plan_status,created_at,updated_at,is_current
0,424,397,2,2,6,2026-06-03 01:53:06+00:00,2026-06-04 05:11:06+00:00,21.0,12800,50,SCHEDULED,2026-05-23 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True

In [16]:
# Cell 15. Product / Line / Line Status 조회

# product_id 보완: prediction에 없고 plan/order에 있으면 보완 시도
if product_id is None:
    for df in [plan_df, order_df]:
        if not df.empty and "product_id" in df.columns:
            product_id = df.iloc[0]["product_id"]
            break

# line_id 보완: prediction에 없고 plan에 있으면 보완 시도
if line_id is None:
    for col_candidate in ["line_id", "assigned_line_id", "primary_line_id"]:
        if not plan_df.empty and col_candidate in plan_df.columns:
            line_id = plan_df.iloc[0][col_candidate]
            break


def load_line_status_for_context(line_id, product_id=None, plan_id=None) -> pd.DataFrame:
    """
    line_status 조회 우선순위:
    1. plan_id가 일치하는 상태
    2. line_id + product_id가 일치하는 상태
    3. line_id 기준 current_yield_rate가 존재하는 최신 상태
    4. line_id 기준 최신 상태
    """

    if not has_table("line_status") or line_id is None:
        return pd.DataFrame()

    order_col = "recorded_at" if has_col("line_status", "recorded_at") else None

    # 1. plan_id 기준
    if plan_id is not None and has_col("line_status", "plan_id"):
        sql = f"""
            SELECT *
            FROM {tref_by_key("line_status")}
            WHERE {q("plan_id")} = :plan_id
        """
        if order_col:
            sql += f"\nORDER BY {q(order_col)} DESC"
        sql += "\nLIMIT 1"

        df = read_df(sql, {"plan_id": plan_id})
        if not df.empty:
            return df

    # 2. line_id + product_id 기준
    if product_id is not None and has_col("line_status", "product_id"):
        sql = f"""
            SELECT *
            FROM {tref_by_key("line_status")}
            WHERE {q("line_id")} = :line_id
              AND {q("product_id")} = :product_id
        """
        if order_col:
            sql += f"\nORDER BY {q(order_col)} DESC"
        sql += "\nLIMIT 1"

        df = read_df(sql, {"line_id": line_id, "product_id": product_id})
        if not df.empty:
            return df

    # 3. line_id 기준 current_yield_rate가 존재하는 최신 상태
    if has_col("line_status", "current_yield_rate"):
        sql = f"""
            SELECT *
            FROM {tref_by_key("line_status")}
            WHERE {q("line_id")} = :line_id
              AND {q("current_yield_rate")} IS NOT NULL
        """
        if order_col:
            sql += f"\nORDER BY {q(order_col)} DESC"
        sql += "\nLIMIT 1"

        df = read_df(sql, {"line_id": line_id})
        if not df.empty:
            return df

    # 4. line_id 기준 최신 상태
    sql = f"""
        SELECT *
        FROM {tref_by_key("line_status")}
        WHERE {q("line_id")} = :line_id
    """
    if order_col:
        sql += f"\nORDER BY {q(order_col)} DESC"
    sql += "\nLIMIT 1"

    return read_df(sql, {"line_id": line_id})


product_df = (
    read_by_equal("products", "product_id", product_id, limit=1)
    if product_id is not None
    else pd.DataFrame()
)

line_df = (
    read_by_equal("production_lines", "line_id", line_id, limit=1)
    if line_id is not None
    else pd.DataFrame()
)

line_status_df = load_line_status_for_context(
    line_id=line_id,
    product_id=product_id,
    plan_id=plan_id,
)

print("product_id:", product_id)
print("line_id:", line_id)
print("product_df:", product_df.shape)
print("line_df:", line_df.shape)
print("line_status_df:", line_status_df.shape)

display(product_df)
display(line_df)
display(line_status_df)

product_id: 2
line_id: 2
product_df: (1, 9)
line_df: (1, 9)
line_status_df: (1, 15)

,product_id,product_code,product_name,product_category,unit,average_yield_rate,min_production_quantity,description,updated_at
0,2,ABS-WHT,ABS-WHITE,ABS,KG,0.938,1000,"WHITE 색상 ABS 컴파운드 제품, 색상 오염 관리 필요",2026-03-31 15:00:00+00:00

,line_id,line_code,line_name,max_capacity_per_day,capacity_unit,supports_changeover,is_active,description,updated_at
0,2,LINE-ABS-02,ABS 보조 생산 Line,15000,KG,True,True,ABS 계열 보조 생산 및 긴급 주문 대응을 위한 Batch 생산 Line,2026-03-31 15:00:00+00:00

,line_status_id,line_id,product_id,plan_id,operator_id,recorded_at,operation_status,throughput_rate,current_yield_rate,waiting_quantity,waiting_time_hr,processed_quantity,defect_quantity,utilization_rate,progress_rate
0,2,2,1,401,7,2026-06-01 00:00:00+00:00,RUNNING,0.79,0.937,2100,1.7,9513,599,0.81,0.4686

In [17]:
# Cell 16. Plan Materials / Material Inventories / Materials 조회

# plan_id 보완
if plan_id is None and not plan_df.empty and "plan_id" in plan_df.columns:
    plan_id = plan_df.iloc[0]["plan_id"]

plan_materials_df = (
    read_by_equal(
        logical_table_key="production_plan_materials",
        column_name="plan_id",
        value=plan_id,
        limit=100,
    )
    if plan_id is not None
    else pd.DataFrame()
)

material_ids = []
if not plan_materials_df.empty and "material_id" in plan_materials_df.columns:
    material_ids = plan_materials_df["material_id"].dropna().drop_duplicates().tolist()

material_inventories_df = (
    read_by_in(
        logical_table_key="material_inventories",
        column_name="material_id",
        values=material_ids,
        limit=200,
    )
    if material_ids
    else pd.DataFrame()
)

materials_df = (
    read_by_in(
        logical_table_key="materials",
        column_name="material_id",
        values=material_ids,
        limit=200,
    )
    if material_ids
    else pd.DataFrame()
)

print("plan_id:", plan_id)
print("material_ids:", material_ids)
print("plan_materials_df:", plan_materials_df.shape)
print("material_inventories_df:", material_inventories_df.shape)
print("materials_df:", materials_df.shape)

display(plan_materials_df)
display(material_inventories_df)
display(materials_df)

plan_id: 424
material_ids: [2, 3, 10, 17, 18, 21, 22, 23, 24, 1]
plan_materials_df: (10, 12)
material_inventories_df: (10, 12)
materials_df: (10, 7)

,plan_material_id,plan_id,material_id,required_quantity,reserved_quantity,consumed_quantity,shortage_quantity,material_plan_status,created_at,updated_at,ever_had_material_shortage,inbound_delay_days
0,3646,424,2,3296.0000,3296.0000,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
1,3647,424,3,922.8800,922.8800,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
2,3648,424,10,678.4000,678.4000,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
3,3649,424,17,336.0000,336.0000,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
4,3650,424,18,130.5600,130.5600,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
5,3651,424,21,27.6480,27.6480,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
6,3652,424,22,12.9280,12.9280,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
7,3653,424,23,2.5856,2.5856,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
8,3654,424,24,12.9280,12.9280,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
9,3645,424,1,7778.5600,7778.5600,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0

,inventory_id,material_id,current_quantity,available_quantity,reserved_quantity,safety_stock_quantity,expected_inbound_at,expected_inbound_quantity,inventory_status,updated_at,version,created_at
0,1,1,76000.0,25480.3495,50519.6505,30000.0,NaT,NaN,LOW,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
1,2,2,35000.0,14397.8165,20602.1835,22000.0,NaT,NaN,LOW,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
2,3,3,10500.0,4055.1355,6444.8645,9000.0,2026-06-04 00:00:00+00:00,12000.0,LOW,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
3,10,10,5200.0,3315.0550,1884.9450,3000.0,NaT,NaN,NORMAL,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
4,17,17,7800.0,0.0000,7800.0000,3500.0,NaT,NaN,SHORTAGE,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
5,18,18,9200.0,787.9195,8412.0805,3000.0,NaT,NaN,LOW,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
6,21,21,900.0,823.1796,76.8204,500.0,2026-06-03 02:00:00+00:00,1500.0,NORMAL,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
7,22,22,15000.0,14579.8751,420.1249,5000.0,NaT,NaN,NORMAL,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
8,23,23,2200.0,2098.2813,101.7187,1000.0,NaT,NaN,NORMAL,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
9,24,24,15500.0,15079.8751,420.1249,6000.0,NaT,NaN,NORMAL,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00

,material_id,material_code,material_name,material_type,unit,description,updated_at
0,1,MAT-ABS-BASE,ABS Base Resin,BASE_RESIN,KG,ABS 제품 생산용 기본 수지,2026-03-31 15:00:00+00:00
1,2,MAT-SAN-RESIN,SAN Resin,BASE_RESIN,KG,ABS 컴파운딩에 사용되는 SAN 계열 수지,2026-03-31 15:00:00+00:00
2,3,MAT-BR-RUBBER,Butadiene Rubber,BASE_RESIN,KG,ABS 충격 보강용 고무계 원료,2026-03-31 15:00:00+00:00
3,10,MAT-WHITE-MB,White Masterbatch,COLORANT,KG,White 색상 구현용 마스터배치,2026-03-31 15:00:00+00:00
4,17,MAT-STABILIZER,Stabilizer,ADDITIVE,KG,공정 안정화 및 물성 안정용 첨가제,2026-03-31 15:00:00+00:00
5,18,MAT-ANTIOX,Antioxidant,ADDITIVE,KG,산화 방지용 첨가제,2026-03-31 15:00:00+00:00
6,21,MAT-CLEANING,Cleaning Agent,PROCESS_AID,L,제품 전환 시 세척용 공정 보조재,2026-03-31 15:00:00+00:00
7,22,MAT-BAG,Product Bag,PACKAGING,EA,완제품 포장용 Bag,2026-03-31 15:00:00+00:00
8,23,MAT-PALLET,Shipping Pallet,PACKAGING,EA,출하 적재용 Pallet,2026-03-31 15:00:00+00:00
9,24,MAT-LABEL,Product Label,PACKAGING,EA,제품 식별 및 출하 라벨,2026-03-31 15:00:00+00:00

In [18]:
# Cell 17. Machines / Machine Statuses 조회

machines_df = pd.DataFrame()

if line_id is not None:
    # 보통 production_machines에 line_id가 있을 가능성이 큼
    if has_col("production_machines", "line_id"):
        machines_df = read_by_equal(
            logical_table_key="production_machines",
            column_name="line_id",
            value=line_id,
            limit=100,
        )
    # line_id가 없다면 전체 조회하지 않고 일단 비워둡니다.
    else:
        print("production_machines 테이블에 line_id 컬럼이 없어 설비 조회를 건너뜁니다.")

machine_ids = []
if not machines_df.empty and "machine_id" in machines_df.columns:
    machine_ids = machines_df["machine_id"].dropna().drop_duplicates().tolist()

machine_statuses_df = (
    read_by_in(
        logical_table_key="machine_statuses",
        column_name="machine_id",
        values=machine_ids,
        limit=200,
    )
    if machine_ids
    else pd.DataFrame()
)

print("machine_ids:", machine_ids)
print("machines_df:", machines_df.shape)
print("machine_statuses_df:", machine_statuses_df.shape)

display(machines_df)
display(machine_statuses_df)

machine_ids: [6, 7, 8, 9, 10]
machines_df: (5, 8)
machine_statuses_df: (5, 11)

,machine_id,line_id,machine_code,machine_name,machine_type,machine_role,machine_order,updated_at
0,6,2,M-ABS02-FEED,ABS-02 원료 투입기,FEEDER,ABS 계열 원료 투입 및 계량,1,2026-03-31 15:00:00+00:00
1,7,2,M-ABS02-MIX,ABS-02 컴파운딩 믹서,MIXER,ABS 수지·고무·첨가제 혼합,2,2026-03-31 15:00:00+00:00
2,8,2,M-ABS02-EXT,ABS-02 압출기,EXTRUDER,ABS 컴파운드 압출 및 성형,3,2026-03-31 15:00:00+00:00
3,9,2,M-ABS02-COOL,ABS-02 냉각 절단기,COOLER,압출물 냉각 및 절단,4,2026-03-31 15:00:00+00:00
4,10,2,M-ABS02-PACK,ABS-02 검사 포장기,PACKER,품질 검사 및 포장,5,2026-03-31 15:00:00+00:00

,machine_status_id,machine_id,line_id,plan_id,product_id,recorded_at,operation_status,processed_quantity,defect_quantity,status_note,updated_at
0,6,6,2,401,1,2026-06-01 00:00:00+00:00,RUNNING,9894,90,라인 생산계획에 따라 정상 가동 중,2026-06-01 00:00:00+00:00
1,7,7,2,401,1,2026-06-01 00:00:00+00:00,RUNNING,9703,210,라인 생산계획에 따라 정상 가동 중,2026-06-01 00:00:00+00:00
2,8,8,2,401,1,2026-06-01 00:00:00+00:00,RUNNING,9513,599,라인 생산계획에 따라 정상 가동 중,2026-06-01 00:00:00+00:00
3,9,9,2,401,1,2026-06-01 00:00:00+00:00,RUNNING,9323,389,라인 생산계획에 따라 정상 가동 중,2026-06-01 00:00:00+00:00
4,10,10,2,401,1,2026-06-01 00:00:00+00:00,RUNNING,9037,689,포장 대기 물량 증가로 처리량 모니터링 필요,2026-06-01 00:00:00+00:00

In [19]:
# Cell 18. Production Results 조회

production_results_df = pd.DataFrame()

if has_table("production_results"):
    if plan_id is not None and has_col("production_results", "plan_id"):
        production_results_df = read_by_equal(
            logical_table_key="production_results",
            column_name="plan_id",
            value=plan_id,
            limit=50,
        )

    if (
        production_results_df.empty
        and order_id is not None
        and has_col("production_results", "order_id")
    ):
        production_results_df = read_by_equal(
            logical_table_key="production_results",
            column_name="order_id",
            value=order_id,
            limit=50,
        )

print("production_results_df:", production_results_df.shape)
display(production_results_df)

production_results_df: (0, 20)

Empty DataFrame
Columns: [result_id, plan_id, order_id, product_id, line_id, planned_start_at, actual_start_at, planned_end_at, actual_end_at, planned_quantity, actual_quantity, defect_quantity, yield_rate, actual_duration_hr, actual_setup_time_hr, actual_delay_hr, is_delayed, actual_delay_reason, result_status, updated_at]
Index: []

In [20]:
# Cell 19. Risk Context 객체 구성

risk_context = {
    "agent_input": agent_input,
    "ids": {
        "prediction_id": prediction_id,
        "order_id": order_id,
        "plan_id": plan_id,
        "product_id": product_id,
        "line_id": line_id,
        "material_ids": material_ids,
        "machine_ids": machine_ids,
    },
    "tables": {
        "prediction": prediction_df,
        "order": order_df,
        "plan": plan_df,
        "product": product_df,
        "line": line_df,
        "line_status": line_status_df,
        "plan_materials": plan_materials_df,
        "material_inventories": material_inventories_df,
        "materials": materials_df,
        "machines": machines_df,
        "machine_statuses": machine_statuses_df,
        "production_results": production_results_df,
    },
}

print("risk_context 생성 완료")
print("ids:")
risk_context["ids"]

risk_context 생성 완료
ids:

{'prediction_id': 13,
 'order_id': 397,
 'plan_id': 424,
 'product_id': 2,
 'line_id': 2,
 'material_ids': [2, 3, 10, 17, 18, 21, 22, 23, 24, 1],
 'machine_ids': [6, 7, 8, 9, 10]}

In [21]:
# Cell 20. Context Load 결과 요약

summary_rows = []

for name, df in risk_context["tables"].items():
    summary_rows.append(
        {
            "context_key": name,
            "row_count": len(df),
            "column_count": len(df.columns) if isinstance(df, pd.DataFrame) else None,
            "loaded": isinstance(df, pd.DataFrame) and not df.empty,
        }
    )

context_summary_df = pd.DataFrame(summary_rows)
display(context_summary_df)

print("다음 단계 진행 가능 여부 점검")

required_context_keys = [
    "prediction",
    "order",
    "plan",
]

missing_required = [key for key in required_context_keys if risk_context["tables"][key].empty]

if missing_required:
    print("필수 context 누락:", missing_required)
    print("이 경우 다음 Analyzer 계산 전에 조회 조건 또는 테이블/컬럼명을 조정해야 합니다.")
else:
    print("필수 context 로드 완료")
    print("다음 단계: Analyzer Node 구현 가능")

             context_key  row_count  column_count  loaded
0             prediction          1            16    True
1                  order          1            13    True
2                   plan          1            14    True
3                product          1             9    True
4                   line          1             9    True
5            line_status          1            15    True
6         plan_materials         10            12    True
7   material_inventories         10            12    True
8              materials         10             7    True
9               machines          5             8    True
10      machine_statuses          5            11    True
11    production_results          0            20   False

다음 단계 진행 가능 여부 점검
필수 context 로드 완료
다음 단계: Analyzer Node 구현 가능

## Materials Node

In [22]:
# Cell 21. Material 관련 데이터 확인

material_context_keys = [
    "plan_materials",
    "material_inventories",
    "materials",
    "plan",
]

for key in material_context_keys:
    df = risk_context["tables"].get(key)
    print("\n" + "=" * 100)
    print(f"[{key}] shape={df.shape if isinstance(df, pd.DataFrame) else None}")

    if isinstance(df, pd.DataFrame) and not df.empty:
        print("columns:")
        print(list(df.columns))
        display(df.head(10))
    else:
        print("데이터 없음")

====================================================================================================
[plan_materials] shape=(10, 12)
columns:
['plan_material_id', 'plan_id', 'material_id', 'required_quantity', 'reserved_quantity', 'consumed_quantity', 'shortage_quantity', 'material_plan_status', 'created_at', 'updated_at', 'ever_had_material_shortage', 'inbound_delay_days']

,plan_material_id,plan_id,material_id,required_quantity,reserved_quantity,consumed_quantity,shortage_quantity,material_plan_status,created_at,updated_at,ever_had_material_shortage,inbound_delay_days
0,3646,424,2,3296.0000,3296.0000,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
1,3647,424,3,922.8800,922.8800,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
2,3648,424,10,678.4000,678.4000,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
3,3649,424,17,336.0000,336.0000,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
4,3650,424,18,130.5600,130.5600,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
5,3651,424,21,27.6480,27.6480,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
6,3652,424,22,12.9280,12.9280,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
7,3653,424,23,2.5856,2.5856,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
8,3654,424,24,12.9280,12.9280,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0
9,3645,424,1,7778.5600,7778.5600,None,0.0,READY,2026-05-23 00:00:00+00:00,2026-06-09 07:22:57.900407+00:00,False,0.0

====================================================================================================
[material_inventories] shape=(10, 12)
columns:
['inventory_id', 'material_id', 'current_quantity', 'available_quantity', 'reserved_quantity', 'safety_stock_quantity', 'expected_inbound_at', 'expected_inbound_quantity', 'inventory_status', 'updated_at', 'version', 'created_at']

,inventory_id,material_id,current_quantity,available_quantity,reserved_quantity,safety_stock_quantity,expected_inbound_at,expected_inbound_quantity,inventory_status,updated_at,version,created_at
0,1,1,76000.0,25480.3495,50519.6505,30000.0,NaT,NaN,LOW,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
1,2,2,35000.0,14397.8165,20602.1835,22000.0,NaT,NaN,LOW,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
2,3,3,10500.0,4055.1355,6444.8645,9000.0,2026-06-04 00:00:00+00:00,12000.0,LOW,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
3,10,10,5200.0,3315.0550,1884.9450,3000.0,NaT,NaN,NORMAL,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
4,17,17,7800.0,0.0000,7800.0000,3500.0,NaT,NaN,SHORTAGE,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
5,18,18,9200.0,787.9195,8412.0805,3000.0,NaT,NaN,LOW,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
6,21,21,900.0,823.1796,76.8204,500.0,2026-06-03 02:00:00+00:00,1500.0,NORMAL,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
7,22,22,15000.0,14579.8751,420.1249,5000.0,NaT,NaN,NORMAL,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
8,23,23,2200.0,2098.2813,101.7187,1000.0,NaT,NaN,NORMAL,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00
9,24,24,15500.0,15079.8751,420.1249,6000.0,NaT,NaN,NORMAL,2026-06-09 07:22:57.900407+00:00,None,2026-06-01 00:00:00+00:00

====================================================================================================
[materials] shape=(10, 7)
columns:
['material_id', 'material_code', 'material_name', 'material_type', 'unit', 'description', 'updated_at']

,material_id,material_code,material_name,material_type,unit,description,updated_at
0,1,MAT-ABS-BASE,ABS Base Resin,BASE_RESIN,KG,ABS 제품 생산용 기본 수지,2026-03-31 15:00:00+00:00
1,2,MAT-SAN-RESIN,SAN Resin,BASE_RESIN,KG,ABS 컴파운딩에 사용되는 SAN 계열 수지,2026-03-31 15:00:00+00:00
2,3,MAT-BR-RUBBER,Butadiene Rubber,BASE_RESIN,KG,ABS 충격 보강용 고무계 원료,2026-03-31 15:00:00+00:00
3,10,MAT-WHITE-MB,White Masterbatch,COLORANT,KG,White 색상 구현용 마스터배치,2026-03-31 15:00:00+00:00
4,17,MAT-STABILIZER,Stabilizer,ADDITIVE,KG,공정 안정화 및 물성 안정용 첨가제,2026-03-31 15:00:00+00:00
5,18,MAT-ANTIOX,Antioxidant,ADDITIVE,KG,산화 방지용 첨가제,2026-03-31 15:00:00+00:00
6,21,MAT-CLEANING,Cleaning Agent,PROCESS_AID,L,제품 전환 시 세척용 공정 보조재,2026-03-31 15:00:00+00:00
7,22,MAT-BAG,Product Bag,PACKAGING,EA,완제품 포장용 Bag,2026-03-31 15:00:00+00:00
8,23,MAT-PALLET,Shipping Pallet,PACKAGING,EA,출하 적재용 Pallet,2026-03-31 15:00:00+00:00
9,24,MAT-LABEL,Product Label,PACKAGING,EA,제품 식별 및 출하 라벨,2026-03-31 15:00:00+00:00

====================================================================================================
[plan] shape=(1, 14)
columns:
['plan_id', 'order_id', 'product_id', 'line_id', 'operator_id', 'planned_start_at', 'planned_end_at', 'estimated_duration_hr', 'planned_quantity', 'plan_sequence', 'plan_status', 'created_at', 'updated_at', 'is_current']

,plan_id,order_id,product_id,line_id,operator_id,planned_start_at,planned_end_at,estimated_duration_hr,planned_quantity,plan_sequence,plan_status,created_at,updated_at,is_current
0,424,397,2,2,6,2026-06-03 01:53:06+00:00,2026-06-04 05:11:06+00:00,21.0,12800,50,SCHEDULED,2026-05-23 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True

In [23]:
# Cell 22. Material Analyzer 유틸리티 정의

import json
from dataclasses import dataclass

import numpy as np
import pandas as pd


@dataclass
class MaterialAnalyzerConfig:
    shortage_ratio_medium: float = 0.05
    shortage_ratio_high: float = 0.20
    inbound_delay_medium_hours: float = 4.0
    inbound_delay_high_hours: float = 24.0


MATERIAL_CONFIG = MaterialAnalyzerConfig()


def first_existing_col(df: pd.DataFrame, candidates: list[str]) -> str | None:
    if df is None or df.empty:
        return None
    cols = set(df.columns)
    for col in candidates:
        if col in cols:
            return col
    return None


def require_col(df: pd.DataFrame, candidates: list[str], df_name: str, semantic_name: str) -> str:
    col = first_existing_col(df, candidates)
    if col is None:
        raise RuntimeError(
            f"[{df_name}]에서 {semantic_name} 컬럼을 찾지 못했습니다.\n"
            f"후보 컬럼: {candidates}\n"
            f"실제 컬럼: {list(df.columns)}\n"
            f"실제 컬럼명을 알려주시면 매핑 후보에 반영하겠습니다."
        )
    return col


def to_number(value, default: float = 0.0) -> float:
    if value is None:
        return default
    try:
        if pd.isna(value):
            return default
    except TypeError:
        pass

    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def to_datetime_or_none(value):
    if value is None:
        return None
    try:
        if pd.isna(value):
            return None
    except TypeError:
        pass

    try:
        return pd.to_datetime(value)
    except Exception:
        return None


def hours_between(later, earlier) -> float | None:
    later_dt = to_datetime_or_none(later)
    earlier_dt = to_datetime_or_none(earlier)

    if later_dt is None or earlier_dt is None:
        return None

    return (later_dt - earlier_dt).total_seconds() / 3600.0


def classify_shortage_severity(shortage_ratio: float) -> str:
    if shortage_ratio >= MATERIAL_CONFIG.shortage_ratio_high:
        return "HIGH"
    if shortage_ratio >= MATERIAL_CONFIG.shortage_ratio_medium:
        return "MEDIUM"
    return "LOW"


def classify_delay_severity(delay_hours: float | None) -> str:
    if delay_hours is None:
        return "UNKNOWN"
    if delay_hours >= MATERIAL_CONFIG.inbound_delay_high_hours:
        return "HIGH"
    if delay_hours >= MATERIAL_CONFIG.inbound_delay_medium_hours:
        return "MEDIUM"
    return "LOW"


def format_qty(value: float) -> str:
    if value is None or pd.isna(value):
        return "확인 필요"
    if abs(value - round(value)) < 1e-9:
        return f"{int(round(value)):,}"
    return f"{value:,.2f}"


def format_pct(value: float) -> str:
    if value is None or pd.isna(value):
        return "확인 필요"
    return f"{value * 100:.1f}%"

In [24]:
# Cell 23. Material Analyzer 컬럼 매핑

plan_materials_df = risk_context["tables"]["plan_materials"].copy()
material_inventories_df = risk_context["tables"]["material_inventories"].copy()
materials_df = risk_context["tables"]["materials"].copy()
plan_df = risk_context["tables"]["plan"].copy()

if plan_materials_df.empty:
    raise RuntimeError("plan_materials 데이터가 없습니다. Material Analyzer를 실행할 수 없습니다.")

if material_inventories_df.empty:
    raise RuntimeError(
        "material_inventories 데이터가 없습니다. Material Analyzer를 실행할 수 없습니다."
    )

# 필수
pm_material_id_col = require_col(
    plan_materials_df, ["material_id", "material_code"], "plan_materials", "자재 ID"
)

inv_material_id_col = require_col(
    material_inventories_df, ["material_id", "material_code"], "material_inventories", "자재 ID"
)

required_qty_col = require_col(
    plan_materials_df,
    [
        "required_qty",
        "required_quantity",
        "required_amount",
        "quantity_required",
        "planned_required_qty",
        "material_required_qty",
        "usage_qty",
        "planned_usage_qty",
        "need_qty",
    ],
    "plan_materials",
    "필요 자재 수량",
)

# 선택
pm_reserved_qty_col = first_existing_col(
    plan_materials_df,
    [
        "reserved_qty",
        "reserved_quantity",
        "allocated_qty",
        "reserved_amount",
        "usable_reserved_qty",
    ],
)

pm_shortage_qty_col = first_existing_col(
    plan_materials_df,
    [
        "shortage_qty",
        "shortage_quantity",
        "material_shortage_qty",
    ],
)

pm_shortage_ratio_col = first_existing_col(
    plan_materials_df,
    [
        "shortage_ratio",
        "material_shortage_ratio",
    ],
)

inv_available_qty_col = first_existing_col(
    material_inventories_df,
    [
        "available_qty",
        "available_quantity",
        "available_stock",
        "available_stock_qty",
    ],
)

inv_current_qty_col = first_existing_col(
    material_inventories_df,
    [
        "current_qty",
        "current_quantity",
        "current_stock",
        "current_stock_qty",
        "stock_qty",
        "inventory_qty",
        "on_hand_qty",
        "quantity",
    ],
)

inv_reserved_qty_col = first_existing_col(
    material_inventories_df,
    [
        "reserved_qty",
        "reserved_quantity",
        "reserved_stock",
        "reserved_stock_qty",
        "allocated_qty",
        "allocated_stock_qty",
    ],
)

inv_inbound_qty_col = first_existing_col(
    material_inventories_df,
    [
        "inbound_qty",
        "inbound_quantity",
        "incoming_qty",
        "incoming_quantity",
        "expected_inbound_qty",
        "scheduled_inbound_qty",
        "ordered_qty",
    ],
)

inv_inbound_at_col = first_existing_col(
    material_inventories_df,
    [
        "expected_inbound_at",
        "inbound_expected_at",
        "inbound_at",
        "next_inbound_at",
        "expected_arrival_at",
        "arrival_expected_at",
        "inbound_date",
    ],
)

material_name_col = first_existing_col(
    materials_df,
    [
        "material_name",
        "name",
        "material_nm",
    ],
)

material_code_col = first_existing_col(
    materials_df,
    [
        "material_code",
        "code",
    ],
)

pm_required_at_col = first_existing_col(
    plan_materials_df,
    [
        "material_required_at",
        "required_at",
        "needed_at",
        "need_at",
    ],
)

plan_start_col = first_existing_col(
    plan_df,
    [
        "planned_start_at",
        "start_at",
        "scheduled_start_at",
        "production_start_at",
    ],
)

print("Material Analyzer 컬럼 매핑 결과")
mapping_result = {
    "pm_material_id_col": pm_material_id_col,
    "inv_material_id_col": inv_material_id_col,
    "required_qty_col": required_qty_col,
    "pm_reserved_qty_col": pm_reserved_qty_col,
    "pm_shortage_qty_col": pm_shortage_qty_col,
    "pm_shortage_ratio_col": pm_shortage_ratio_col,
    "inv_available_qty_col": inv_available_qty_col,
    "inv_current_qty_col": inv_current_qty_col,
    "inv_reserved_qty_col": inv_reserved_qty_col,
    "inv_inbound_qty_col": inv_inbound_qty_col,
    "inv_inbound_at_col": inv_inbound_at_col,
    "material_name_col": material_name_col,
    "material_code_col": material_code_col,
    "pm_required_at_col": pm_required_at_col,
    "plan_start_col": plan_start_col,
}

mapping_result

Material Analyzer 컬럼 매핑 결과

{'pm_material_id_col': 'material_id',
 'inv_material_id_col': 'material_id',
 'required_qty_col': 'required_quantity',
 'pm_reserved_qty_col': 'reserved_quantity',
 'pm_shortage_qty_col': 'shortage_quantity',
 'pm_shortage_ratio_col': None,
 'inv_available_qty_col': 'available_quantity',
 'inv_current_qty_col': 'current_quantity',
 'inv_reserved_qty_col': 'reserved_quantity',
 'inv_inbound_qty_col': None,
 'inv_inbound_at_col': 'expected_inbound_at',
 'material_name_col': 'material_name',
 'material_code_col': 'material_code',
 'pm_required_at_col': None,
 'plan_start_col': 'planned_start_at'}

In [25]:
# Cell 24. Material Analyzer 함수 정의


def get_material_display_name(material_id, materials_df: pd.DataFrame) -> str:
    if materials_df.empty or pm_material_id_col is None:
        return str(material_id)

    # materials 테이블의 id 컬럼명은 plan_materials와 같을 가능성이 높지만,
    # inv_material_id_col 또는 material_id 후보로 다시 확인합니다.
    mat_id_col = first_existing_col(materials_df, ["material_id", "material_code"])
    if mat_id_col is None:
        return str(material_id)

    matched = materials_df[materials_df[mat_id_col] == material_id]
    if matched.empty:
        return str(material_id)

    row = matched.iloc[0]

    code = row.get(material_code_col) if material_code_col else None
    name = row.get(material_name_col) if material_name_col else None

    if code and name:
        return f"{code}({name})"
    if name:
        return str(name)
    if code:
        return str(code)

    return str(material_id)


def get_inventory_row(material_id, inventory_df: pd.DataFrame) -> pd.Series | None:
    if inventory_df.empty:
        return None

    matched = inventory_df[inventory_df[inv_material_id_col] == material_id]

    if matched.empty:
        return None

    return matched.iloc[0]


def get_material_required_at(pm_row: pd.Series, plan_df: pd.DataFrame):
    if pm_required_at_col:
        value = pm_row.get(pm_required_at_col)
        if to_datetime_or_none(value) is not None:
            return value

    if not plan_df.empty and plan_start_col:
        return plan_df.iloc[0].get(plan_start_col)

    return None


def calculate_available_qty(pm_row: pd.Series, inv_row: pd.Series | None) -> dict[str, float]:
    """
    available_qty 계산 원칙:
    1. inventory에 available_qty 계열 컬럼이 있으면 우선 사용
    2. 없으면 current_qty - inventory_reserved_qty
    3. plan_materials의 reserved_qty는 해당 계획에 이미 확보된 수량으로 보고
       usable_reserved_qty로 더함
    """
    plan_reserved_qty = (
        to_number(pm_row.get(pm_reserved_qty_col), 0.0) if pm_reserved_qty_col else 0.0
    )

    if inv_row is None:
        return {
            "inventory_base_available_qty": 0.0,
            "plan_reserved_qty": plan_reserved_qty,
            "effective_available_qty": plan_reserved_qty,
            "current_qty": 0.0,
            "inventory_reserved_qty": 0.0,
        }

    if inv_available_qty_col:
        inventory_base_available_qty = to_number(inv_row.get(inv_available_qty_col), 0.0)
        current_qty = (
            to_number(inv_row.get(inv_current_qty_col), 0.0)
            if inv_current_qty_col
            else inventory_base_available_qty
        )
        inventory_reserved_qty = (
            to_number(inv_row.get(inv_reserved_qty_col), 0.0) if inv_reserved_qty_col else 0.0
        )
    else:
        current_qty = (
            to_number(inv_row.get(inv_current_qty_col), 0.0) if inv_current_qty_col else 0.0
        )
        inventory_reserved_qty = (
            to_number(inv_row.get(inv_reserved_qty_col), 0.0) if inv_reserved_qty_col else 0.0
        )
        inventory_base_available_qty = max(current_qty - inventory_reserved_qty, 0.0)

    effective_available_qty = inventory_base_available_qty + plan_reserved_qty

    return {
        "inventory_base_available_qty": inventory_base_available_qty,
        "plan_reserved_qty": plan_reserved_qty,
        "effective_available_qty": effective_available_qty,
        "current_qty": current_qty,
        "inventory_reserved_qty": inventory_reserved_qty,
    }


def run_material_analyzer(risk_context: dict[str, Any]) -> dict[str, Any]:
    plan_materials_df = risk_context["tables"]["plan_materials"].copy()
    material_inventories_df = risk_context["tables"]["material_inventories"].copy()
    materials_df = risk_context["tables"]["materials"].copy()
    plan_df = risk_context["tables"]["plan"].copy()

    cause_candidates = []
    material_detail_rows = []
    missing_inventory_materials = []
    shortage_mismatch_materials = []

    for _, pm_row in plan_materials_df.iterrows():
        material_id = pm_row.get(pm_material_id_col)
        material_name = get_material_display_name(material_id, materials_df)

        required_qty = to_number(pm_row.get(required_qty_col), 0.0)
        inv_row = get_inventory_row(material_id, material_inventories_df)

        if inv_row is None:
            missing_inventory_materials.append(material_id)

        availability = calculate_available_qty(pm_row, inv_row)
        effective_available_qty = availability["effective_available_qty"]

        # shortage_qty는 현재 재고 기준으로 직접 계산합니다.
        # DB의 shortage_quantity는 과거 계산값일 수 있으므로 판단 기준으로 사용하지 않습니다.
        calculated_shortage_qty = max(required_qty - effective_available_qty, 0.0)
        shortage_qty = calculated_shortage_qty

        db_shortage_qty = None

        if pm_shortage_qty_col:
            db_shortage_qty = to_number(pm_row.get(pm_shortage_qty_col), 0.0)

        if db_shortage_qty is not None and abs(db_shortage_qty - calculated_shortage_qty) > 1e-6:
            shortage_mismatch_materials.append(
                {
                    "material_id": material_id,
                    "material_name": material_name,
                    "db_shortage_qty": db_shortage_qty,
                    "calculated_shortage_qty": calculated_shortage_qty,
                }
            )

        if pm_shortage_ratio_col:
            shortage_ratio = to_number(pm_row.get(pm_shortage_ratio_col), 0.0)
            # DB 값이 12.0처럼 퍼센트 단위일 가능성을 방어
            if shortage_ratio > 1.0:
                shortage_ratio = shortage_ratio / 100.0
        else:
            shortage_ratio = shortage_qty / required_qty if required_qty > 0 else 0.0

        inbound_qty = (
            to_number(inv_row.get(inv_inbound_qty_col), 0.0)
            if inv_row is not None and inv_inbound_qty_col
            else 0.0
        )
        inbound_at = (
            inv_row.get(inv_inbound_at_col) if inv_row is not None and inv_inbound_at_col else None
        )
        material_required_at = get_material_required_at(pm_row, plan_df)
        inbound_delay_hours = hours_between(inbound_at, material_required_at)

        material_detail_rows.append(
            {
                "material_id": material_id,
                "material_name": material_name,
                "required_qty": required_qty,
                "current_qty": availability["current_qty"],
                "inventory_reserved_qty": availability["inventory_reserved_qty"],
                "inventory_base_available_qty": availability["inventory_base_available_qty"],
                "plan_reserved_qty": availability["plan_reserved_qty"],
                "effective_available_qty": effective_available_qty,
                "shortage_qty": shortage_qty,
                "shortage_ratio": shortage_ratio,
                "inbound_qty": inbound_qty,
                "inbound_at": inbound_at,
                "material_required_at": material_required_at,
                "inbound_delay_hours": inbound_delay_hours,
                "db_shortage_qty": db_shortage_qty,
                "calculated_shortage_qty": calculated_shortage_qty,
                "shortage_qty_mismatch": (
                    db_shortage_qty is not None
                    and abs(db_shortage_qty - calculated_shortage_qty) > 1e-6
                ),
            }
        )

        # MATERIAL_SHORTAGE 후보
        if shortage_qty > 0:
            severity = classify_shortage_severity(shortage_ratio)

            evidence = [
                (
                    f"{material_name} 필요 수량은 {format_qty(required_qty)}이며, "
                    "생산계획 기준 가용 수량은 "
                    f"{format_qty(effective_available_qty)}입니다."
                ),
                (
                    f"{material_name} 부족 수량은 {format_qty(shortage_qty)}이며, "
                    f"부족 비율은 {format_pct(shortage_ratio)}입니다."
                ),
            ]

            if availability["plan_reserved_qty"] > 0:
                evidence.append(
                    "해당 계획에 예약된 수량 "
                    f"{format_qty(availability['plan_reserved_qty'])}을 "
                    "가용 수량에 반영했습니다."
                )

            cause_candidates.append(
                {
                    "cause_type": "MATERIAL_SHORTAGE",
                    "korean_name": "자재 부족",
                    "priority_band": "BLOCKER",
                    "severity": severity,
                    "delay_contribution_hours": None,
                    "delay_contribution_note": (
                        "자재 부족은 생산 착수 BLOCKER로 판단하며, "
                        "자재별 지연 기여시간은 입고 예정 수량/시각이 "
                        "있을 때만 계산합니다."
                    ),
                    "rank_reason": (
                        "필수 자재의 가용 재고가 필요 수량보다 부족하여 "
                        "생산 착수 자체가 지연될 가능성이 높습니다."
                    ),
                    "evidence": evidence,
                    "metrics": {
                        "material_id": material_id,
                        "material_name": material_name,
                        "required_qty": required_qty,
                        "effective_available_qty": effective_available_qty,
                        "shortage_qty": shortage_qty,
                        "shortage_ratio": shortage_ratio,
                    },
                    "action_hint": (
                        "부족 자재 긴급 입고, 대체 자재 사용 가능 여부, "
                        "또는 생산 시작 시점 조정을 검토합니다."
                    ),
                }
            )

        # MATERIAL_DELAY 후보
        # 부족분이 있고, 입고 수량이 부족분을 충족할 수 있으며, 입고 시점이 필요 시점보다 늦은 경우
        if (
            shortage_qty > 0
            and inbound_qty >= shortage_qty
            and inbound_delay_hours is not None
            and inbound_delay_hours > 0
        ):
            severity = classify_delay_severity(inbound_delay_hours)

            evidence = [
                (
                    f"{material_name} 입고 예정 수량 {format_qty(inbound_qty)}은 "
                    f"부족 수량 {format_qty(shortage_qty)}을 충족할 수 있습니다."
                ),
                (
                    "다만 입고 예정 시점이 생산 필요 시점보다 약 "
                    f"{inbound_delay_hours:.1f}시간 늦습니다."
                ),
            ]

            cause_candidates.append(
                {
                    "cause_type": "MATERIAL_DELAY",
                    "korean_name": "자재 입고 지연",
                    "priority_band": "TIME_CRITICAL",
                    "severity": severity,
                    "delay_contribution_hours": inbound_delay_hours,
                    "rank_reason": (
                        "부족 자재가 입고될 예정이지만 생산 필요 시점보다 늦어 "
                        "계획된 생산 시작이 지연될 수 있습니다."
                    ),
                    "evidence": evidence,
                    "metrics": {
                        "material_id": material_id,
                        "material_name": material_name,
                        "shortage_qty": shortage_qty,
                        "inbound_qty": inbound_qty,
                        "inbound_at": str(inbound_at),
                        "material_required_at": str(material_required_at),
                        "inbound_delay_hours": inbound_delay_hours,
                    },
                    "action_hint": (
                        "입고 일정 단축 가능 여부를 확인하거나, 생산 순서 조정으로 "
                        "입고 대기 시간을 흡수할 수 있는지 검토합니다."
                    ),
                }
            )

    material_detail_df = pd.DataFrame(material_detail_rows)

    data_quality_notes = []
    if missing_inventory_materials:
        data_quality_notes.append(
            "material_inventories에서 재고 정보를 찾지 못한 자재가 있습니다: "
            f"{missing_inventory_materials}"
        )

    if inv_inbound_at_col is None:
        data_quality_notes.append(
            "입고 예정 시각 컬럼을 찾지 못해 MATERIAL_DELAY 판단이 제한됩니다."
        )

    if inv_inbound_qty_col is None:
        data_quality_notes.append(
            "입고 예정 수량 컬럼을 찾지 못해 MATERIAL_DELAY 판단이 제한됩니다."
        )

    if pm_required_at_col is None and plan_start_col is None:
        data_quality_notes.append(
            "자재 필요 시점 또는 계획 시작 시각 컬럼을 찾지 못해 MATERIAL_DELAY 판단이 제한됩니다."
        )

    if shortage_mismatch_materials:
        data_quality_notes.append(
            "production_plan_materials.shortage_quantity와 현재 재고 기준 "
            f"계산값이 다른 자재가 있습니다: {shortage_mismatch_materials}"
        )

    return {
        "analyzer": "MaterialAnalyzer",
        "status": "COMPLETED",
        "cause_candidates": cause_candidates,
        "detail_df": material_detail_df,
        "data_quality": {
            "status": "OK" if not data_quality_notes else "PARTIAL",
            "notes": data_quality_notes,
        },
        "column_mapping": mapping_result,
    }


print("Material Analyzer 함수 정의 완료")

Material Analyzer 함수 정의 완료

In [26]:
# Cell 25. Material Analyzer 실행

material_analysis = run_material_analyzer(risk_context)

print("Material Analyzer status:", material_analysis["status"])
print("Data quality:", material_analysis["data_quality"])

print("\n자재 상세 계산 결과")
display(material_analysis["detail_df"])

print("\n원인 후보 수:", len(material_analysis["cause_candidates"]))

if material_analysis["cause_candidates"]:
    for idx, candidate in enumerate(material_analysis["cause_candidates"], start=1):
        print("\n" + "-" * 100)
        print(f"[Candidate {idx}] {candidate['cause_type']} / {candidate['korean_name']}")
        print("priority_band:", candidate["priority_band"])
        print("severity:", candidate["severity"])
        print("delay_contribution_hours:", candidate["delay_contribution_hours"])
        print("rank_reason:", candidate["rank_reason"])
        print("evidence:")
        for ev in candidate["evidence"]:
            print("-", ev)
else:
    print("Material 관련 원인 후보가 없습니다.")

Material Analyzer status: COMPLETED
Data quality: {'status': 'PARTIAL', 'notes': ['입고 예정 수량 컬럼을 찾지 못해 MATERIAL_DELAY 판단이 제한됩니다.']}

자재 상세 계산 결과

,material_id,material_name,required_qty,current_qty,inventory_reserved_qty,inventory_base_available_qty,plan_reserved_qty,effective_available_qty,shortage_qty,shortage_ratio,inbound_qty,inbound_at,material_required_at,inbound_delay_hours,db_shortage_qty,calculated_shortage_qty,shortage_qty_mismatch
0,2,MAT-SAN-RESIN(SAN Resin),3296.0000,35000.0,20602.1835,14397.8165,3296.0000,17693.8165,0.0,0.0,0.0,NaT,2026-06-03 01:53:06+00:00,NaN,0.0,0.0,False
1,3,MAT-BR-RUBBER(Butadiene Rubber),922.8800,10500.0,6444.8645,4055.1355,922.8800,4978.0155,0.0,0.0,0.0,2026-06-04 00:00:00+00:00,2026-06-03 01:53:06+00:00,22.115,0.0,0.0,False
2,10,MAT-WHITE-MB(White Masterbatch),678.4000,5200.0,1884.9450,3315.0550,678.4000,3993.4550,0.0,0.0,0.0,NaT,2026-06-03 01:53:06+00:00,NaN,0.0,0.0,False
3,17,MAT-STABILIZER(Stabilizer),336.0000,7800.0,7800.0000,0.0000,336.0000,336.0000,0.0,0.0,0.0,NaT,2026-06-03 01:53:06+00:00,NaN,0.0,0.0,False
4,18,MAT-ANTIOX(Antioxidant),130.5600,9200.0,8412.0805,787.9195,130.5600,918.4795,0.0,0.0,0.0,NaT,2026-06-03 01:53:06+00:00,NaN,0.0,0.0,False
5,21,MAT-CLEANING(Cleaning Agent),27.6480,900.0,76.8204,823.1796,27.6480,850.8276,0.0,0.0,0.0,2026-06-03 02:00:00+00:00,2026-06-03 01:53:06+00:00,0.115,0.0,0.0,False
6,22,MAT-BAG(Product Bag),12.9280,15000.0,420.1249,14579.8751,12.9280,14592.8031,0.0,0.0,0.0,NaT,2026-06-03 01:53:06+00:00,NaN,0.0,0.0,False
7,23,MAT-PALLET(Shipping Pallet),2.5856,2200.0,101.7187,2098.2813,2.5856,2100.8669,0.0,0.0,0.0,NaT,2026-06-03 01:53:06+00:00,NaN,0.0,0.0,False
8,24,MAT-LABEL(Product Label),12.9280,15500.0,420.1249,15079.8751,12.9280,15092.8031,0.0,0.0,0.0,NaT,2026-06-03 01:53:06+00:00,NaN,0.0,0.0,False
9,1,MAT-ABS-BASE(ABS Base Resin),7778.5600,76000.0,50519.6505,25480.3495,7778.5600,33258.9095,0.0,0.0,0.0,NaT,2026-06-03 01:53:06+00:00,NaN,0.0,0.0,False

원인 후보 수: 0
Material 관련 원인 후보가 없습니다.

In [27]:
# Cell 26. Material Analyzer 결과 JSON 확인

material_analysis_for_next_node = {
    "analyzer": material_analysis["analyzer"],
    "status": material_analysis["status"],
    "cause_candidates": material_analysis["cause_candidates"],
    "data_quality": material_analysis["data_quality"],
}

print(
    json.dumps(
        material_analysis_for_next_node,
        ensure_ascii=False,
        indent=2,
        default=str,
    )
)

{
  "analyzer": "MaterialAnalyzer",
  "status": "COMPLETED",
  "cause_candidates": [],
  "data_quality": {
    "status": "PARTIAL",
    "notes": [
      "입고 예정 수량 컬럼을 찾지 못해 MATERIAL_DELAY 판단이 제한됩니다."
    ]
  }
}

## Yield Analyzer Node : 수율 관련판단

In [28]:
# Cell 28-1. product_line_capabilities 테이블 추가 조회

# 1. TABLE_MAP에 product_line_capabilities 추가
if "product_line_capability" not in TABLE_MAP:
    if "product_line_capabilities" in available_tables:
        TABLE_MAP["product_line_capability"] = "product_line_capabilities"
    elif "product_line_capability" in available_tables:
        TABLE_MAP["product_line_capability"] = "product_line_capability"
    else:
        TABLE_MAP["product_line_capability"] = None

# 2. TABLE_COLUMNS 갱신
TABLE_COLUMNS["product_line_capability"] = get_table_columns_if_exists(
    TABLE_MAP["product_line_capability"]
)

print("product_line_capability table:", TABLE_MAP["product_line_capability"])
print("columns:", TABLE_COLUMNS["product_line_capability"])

# 3. product_id + line_id 기준 조회
product_id = risk_context["ids"].get("product_id")
line_id = risk_context["ids"].get("line_id")

product_line_capability_df = pd.DataFrame()

if TABLE_MAP["product_line_capability"] is None:
    print("product_line_capabilities 테이블을 찾지 못했습니다.")
else:
    has_product_id = has_col("product_line_capability", "product_id")
    has_line_id = has_col("product_line_capability", "line_id")

    if not has_product_id or not has_line_id:
        print("product_line_capabilities에 product_id 또는 line_id 컬럼이 없습니다.")
        print("columns:", TABLE_COLUMNS["product_line_capability"])
    else:
        sql = f"""
            SELECT *
            FROM {tref_by_key("product_line_capability")}
            WHERE {q("product_id")} = :product_id
              AND {q("line_id")} = :line_id
            LIMIT 1
        """

        product_line_capability_df = read_df(
            sql,
            {
                "product_id": product_id,
                "line_id": line_id,
            },
        )

risk_context["tables"]["product_line_capability"] = product_line_capability_df

print("product_id:", product_id)
print("line_id:", line_id)
print("product_line_capability_df:", product_line_capability_df.shape)

display(product_line_capability_df)

product_line_capability table: product_line_capabilities
columns: ['product_line_id', 'product_id', 'line_id', 'standard_production_time_hr', 'capacity_per_day', 'standard_yield_rate', 'priority_rank', 'updated_at']
product_id: 2
line_id: 2
product_line_capability_df: (1, 8)

,product_line_id,product_id,line_id,standard_production_time_hr,capacity_per_day,standard_yield_rate,priority_rank,updated_at
0,4,2,2,1.92,12500,0.928,2,2026-03-31 15:00:00+00:00

In [29]:
# Cell 29. Yield Analyzer 설정값 정의
# production_results는 사용하지 않습니다.
# 현재 라인/계획/제품 기준 수율만 사용합니다.

from dataclasses import dataclass


@dataclass
class YieldAnalyzerConfig:
    # LOW_YIELD 후보 생성 기준
    # 예: 0.03 = 3%p 차이
    low_yield_gap_threshold: float = 0.03

    # HIGH severity 기준
    # 예: 0.05 = 5%p 차이
    high_yield_gap_threshold: float = 0.05

    # 수율 값이 0 또는 비정상적으로 작을 때 계산 방어용
    min_valid_yield_rate: float = 0.01


YIELD_CONFIG = YieldAnalyzerConfig()

print("Yield Analyzer 설정값")
print(f"LOW_YIELD 판단 기준: {YIELD_CONFIG.low_yield_gap_threshold * 100:.1f}%p 이상 차이")
print(f"HIGH severity 기준: {YIELD_CONFIG.high_yield_gap_threshold * 100:.1f}%p 이상 차이")

Yield Analyzer 설정값
LOW_YIELD 판단 기준: 3.0%p 이상 차이
HIGH severity 기준: 5.0%p 이상 차이

In [30]:
# Cell 30. Yield 관련 현재 데이터 확인

yield_context_keys = [
    "plan",
    "product",
    "line",
    "line_status",
    "product_line_capability",
    "order",
]

for key in yield_context_keys:
    df = risk_context["tables"].get(key)

    print("\n" + "=" * 100)
    print(f"[{key}] shape={df.shape if isinstance(df, pd.DataFrame) else None}")

    if isinstance(df, pd.DataFrame) and not df.empty:
        print("columns:")
        print(list(df.columns))
        display(df.head(10))
    else:
        print("데이터 없음")

====================================================================================================
[plan] shape=(1, 14)
columns:
['plan_id', 'order_id', 'product_id', 'line_id', 'operator_id', 'planned_start_at', 'planned_end_at', 'estimated_duration_hr', 'planned_quantity', 'plan_sequence', 'plan_status', 'created_at', 'updated_at', 'is_current']

,plan_id,order_id,product_id,line_id,operator_id,planned_start_at,planned_end_at,estimated_duration_hr,planned_quantity,plan_sequence,plan_status,created_at,updated_at,is_current
0,424,397,2,2,6,2026-06-03 01:53:06+00:00,2026-06-04 05:11:06+00:00,21.0,12800,50,SCHEDULED,2026-05-23 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True

====================================================================================================
[product] shape=(1, 9)
columns:
['product_id', 'product_code', 'product_name', 'product_category', 'unit', 'average_yield_rate', 'min_production_quantity', 'description', 'updated_at']

,product_id,product_code,product_name,product_category,unit,average_yield_rate,min_production_quantity,description,updated_at
0,2,ABS-WHT,ABS-WHITE,ABS,KG,0.938,1000,"WHITE 색상 ABS 컴파운드 제품, 색상 오염 관리 필요",2026-03-31 15:00:00+00:00

====================================================================================================
[line] shape=(1, 9)
columns:
['line_id', 'line_code', 'line_name', 'max_capacity_per_day', 'capacity_unit', 'supports_changeover', 'is_active', 'description', 'updated_at']

,line_id,line_code,line_name,max_capacity_per_day,capacity_unit,supports_changeover,is_active,description,updated_at
0,2,LINE-ABS-02,ABS 보조 생산 Line,15000,KG,True,True,ABS 계열 보조 생산 및 긴급 주문 대응을 위한 Batch 생산 Line,2026-03-31 15:00:00+00:00

====================================================================================================
[line_status] shape=(1, 15)
columns:
['line_status_id', 'line_id', 'product_id', 'plan_id', 'operator_id', 'recorded_at', 'operation_status', 'throughput_rate', 'current_yield_rate', 'waiting_quantity', 'waiting_time_hr', 'processed_quantity', 'defect_quantity', 'utilization_rate', 'progress_rate']

,line_status_id,line_id,product_id,plan_id,operator_id,recorded_at,operation_status,throughput_rate,current_yield_rate,waiting_quantity,waiting_time_hr,processed_quantity,defect_quantity,utilization_rate,progress_rate
0,2,2,1,401,7,2026-06-01 00:00:00+00:00,RUNNING,0.79,0.937,2100,1.7,9513,599,0.81,0.4686

====================================================================================================
[product_line_capability] shape=(1, 8)
columns:
['product_line_id', 'product_id', 'line_id', 'standard_production_time_hr', 'capacity_per_day', 'standard_yield_rate', 'priority_rank', 'updated_at']

,product_line_id,product_id,line_id,standard_production_time_hr,capacity_per_day,standard_yield_rate,priority_rank,updated_at
0,4,2,2,1.92,12500,0.928,2,2026-03-31 15:00:00+00:00

====================================================================================================
[order] shape=(1, 13)
columns:
['order_id', 'order_no', 'product_id', 'order_quantity', 'customer_name', 'customer_contact_name', 'order_date', 'due_date', 'contract_amount', 'late_penalty_amount', 'order_status', 'created_at', 'updated_at']

,order_id,order_no,product_id,order_quantity,customer_name,customer_contact_name,order_date,due_date,contract_amount,late_penalty_amount,order_status,created_at,updated_at
0,397,ORD-202605-027,2,12800,H케미칼,한지우,2026-05-23,2026-06-21,33262380.0,1970292.0,IN_PROGRESS,2026-05-23 00:00:00+00:00,2026-05-23 00:00:00+00:00

In [31]:
# Cell 31. Yield Analyzer 유틸리티 정의

import json
from typing import Any

import pandas as pd


def to_number_safe(value, default: float = np.nan) -> float:
    if value is None:
        return default

    try:
        if pd.isna(value):
            return default
    except TypeError:
        pass

    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def normalize_yield_rate(value) -> float | None:
    """
    수율 값 정규화.
    - 0.94 형태면 그대로 사용
    - 94 형태면 0.94로 변환
    """
    if value is None:
        return None

    try:
        if pd.isna(value):
            return None
    except TypeError:
        pass

    try:
        v = float(value)
    except (TypeError, ValueError):
        return None

    if v < 0:
        return None

    # 94 같은 퍼센트 값은 0.94로 변환
    if v > 1.0:
        v = v / 100.0

    # 변환 후에도 1.5를 넘으면 비정상 값으로 봄
    if v > 1.5:
        return None

    return v


def find_rate_from_sources(
    sources: list[tuple[str, pd.DataFrame]],
    candidate_cols: list[str],
) -> tuple[float | None, str | None, str | None]:
    """
    여러 DataFrame에서 후보 컬럼 순서대로 수율 값을 찾습니다.

    return:
      rate_value, source_key, column_name
    """
    for source_key, df in sources:
        if df is None or df.empty:
            continue

        for col in candidate_cols:
            if col in df.columns:
                value = normalize_yield_rate(df.iloc[0].get(col))
                if value is not None:
                    return value, source_key, col

    return None, None, None


def format_rate(rate: float | None) -> str:
    if rate is None or pd.isna(rate):
        return "확인 필요"
    return f"{rate * 100:.1f}%"


def format_pp(gap: float | None) -> str:
    """
    수율 차이는 %가 아니라 %p로 표시합니다.
    예: 0.032 -> 3.2%p
    """
    if gap is None or pd.isna(gap):
        return "확인 필요"
    return f"{gap * 100:.1f}%p"


def format_qty_for_yield(value: float | None) -> str:
    if value is None or pd.isna(value):
        return "확인 필요"

    if abs(value - round(value)) < 1e-9:
        return f"{int(round(value)):,}"

    return f"{value:,.2f}"


def get_plan_or_order_quantity(order_df: pd.DataFrame, plan_df: pd.DataFrame) -> float | None:
    """
    추가 생산량 추정용 수량.
    우선 production_plans의 계획 수량을 보고,
    없으면 customer_orders의 주문 수량을 사용합니다.
    """
    if plan_df is not None and not plan_df.empty:
        for col in [
            "planned_qty",
            "planned_quantity",
            "plan_qty",
            "quantity",
            "target_qty",
            "target_quantity",
        ]:
            if col in plan_df.columns:
                value = to_number_safe(plan_df.iloc[0].get(col))
                if not pd.isna(value):
                    return value

    if order_df is not None and not order_df.empty:
        for col in [
            "order_qty",
            "order_quantity",
            "quantity",
            "requested_qty",
            "requested_quantity",
        ]:
            if col in order_df.columns:
                value = to_number_safe(order_df.iloc[0].get(col))
                if not pd.isna(value):
                    return value

    return None


def get_line_hourly_capacity(line_df: pd.DataFrame, line_status_df: pd.DataFrame) -> float | None:
    """
    추가 생산 시간 추정용 라인 시간당 생산능력.
    line_status에 현재 처리량 계열 컬럼이 있으면 우선 사용하고,
    없으면 production_lines의 hourly/daily capacity를 사용합니다.
    """

    # 1. line_status의 현재 처리량 계열 컬럼 우선
    if line_status_df is not None and not line_status_df.empty:
        row = line_status_df.iloc[0]

        for col in [
            "current_throughput_per_hour",
            "throughput_per_hour",
            "actual_throughput_per_hour",
            "hourly_throughput",
            "current_capacity_per_hour",
        ]:
            if col in line_status_df.columns:
                value = to_number_safe(row.get(col))
                if not pd.isna(value) and value > 0:
                    return value

    # 2. production_lines의 시간당 capacity
    if line_df is not None and not line_df.empty:
        row = line_df.iloc[0]

        for col in [
            "hourly_capacity",
            "capacity_per_hour",
            "hourly_production_capacity",
            "throughput_per_hour",
        ]:
            if col in line_df.columns:
                value = to_number_safe(row.get(col))
                if not pd.isna(value) and value > 0:
                    return value

        # 3. daily capacity가 있으면 24로 나누어 시간당 capacity 추정
        for col in [
            "daily_capacity",
            "capacity_per_day",
            "daily_production_capacity",
            "production_capacity",
            "max_capacity_per_day",
        ]:
            if col in line_df.columns:
                value = to_number_safe(row.get(col))
                if not pd.isna(value) and value > 0:
                    return value / 24.0

    return None


def classify_yield_severity(max_gap: float | None) -> str:
    if max_gap is None:
        return "UNKNOWN"

    if max_gap >= YIELD_CONFIG.high_yield_gap_threshold:
        return "HIGH"

    if max_gap >= YIELD_CONFIG.low_yield_gap_threshold:
        return "MEDIUM"

    return "LOW"


def format_yield_gap_sentence(target_name, target_rate, baseline_name, baseline_rate, threshold):
    gap = baseline_rate - target_rate

    if gap >= threshold:
        return (
            f"{target_name}은 {format_rate(target_rate)}이고 "
            f"{baseline_name}은 {format_rate(baseline_rate)}입니다. "
            f"{target_name}이 {baseline_name}보다 {format_pp(gap)} 낮아 "
            f"LOW_YIELD 판단 기준 {format_pp(threshold)}를 초과합니다."
        )

    if gap > 0:
        return (
            f"{target_name}은 {format_rate(target_rate)}이고 "
            f"{baseline_name}은 {format_rate(baseline_rate)}입니다. "
            f"{target_name}이 {baseline_name}보다 {format_pp(gap)} 낮지만 "
            f"LOW_YIELD 판단 기준 {format_pp(threshold)}에는 미달합니다."
        )

    return (
        f"{target_name}은 {format_rate(target_rate)}이고 "
        f"{baseline_name}은 {format_rate(baseline_rate)}입니다. "
        f"{target_name}이 {baseline_name}보다 {format_pp(abs(gap))} 높아 "
        f"수율 저하로 판단하지 않습니다."
    )

In [32]:
# Cell 32. Yield Analyzer 함수 정의


def run_yield_analyzer(risk_context: dict[str, Any]) -> dict[str, Any]:
    plan_df = risk_context["tables"]["plan"].copy()
    product_df = risk_context["tables"]["product"].copy()
    line_df = risk_context["tables"]["line"].copy()
    line_status_df = risk_context["tables"]["line_status"].copy()
    product_line_capability_df = (
        risk_context["tables"].get("product_line_capability", pd.DataFrame()).copy()
    )
    order_df = risk_context["tables"]["order"].copy()

    data_quality_notes = []
    cause_candidates = []

    # source 우선순위:
    # current_yield_rate는 line_status를 가장 우선합니다.
    # standard_yield_rate는 plan/product/line 순서로 찾습니다.
    # average_yield_rate는 line/product/line_status 순서로 찾습니다.
    current_sources = [
        ("line_status", line_status_df),
        ("line", line_df),
        ("plan", plan_df),
        ("product", product_df),
    ]

    standard_sources = [
        ("product_line_capability", product_line_capability_df),
        ("plan", plan_df),
        ("product", product_df),
        ("line", line_df),
        ("line_status", line_status_df),
    ]

    average_sources = [
        ("product_line_capability", product_line_capability_df),
        ("line", line_df),
        ("product", product_df),
        ("line_status", line_status_df),
        ("plan", plan_df),
    ]

    current_yield_rate, current_source, current_col = find_rate_from_sources(
        current_sources,
        [
            "current_yield_rate",
            "current_yield",
            "actual_yield_rate",
            "actual_yield",
            "yield_rate",
        ],
    )

    standard_yield_rate, standard_source, standard_col = find_rate_from_sources(
        standard_sources,
        [
            "standard_yield_rate",
            "standard_yield",
            "target_yield_rate",
            "target_yield",
            "expected_yield_rate",
            "expected_yield",
            "planned_yield_rate",
            "planned_yield",
        ],
    )

    average_yield_rate, average_source, average_col = find_rate_from_sources(
        average_sources,
        [
            "average_yield_rate",
            "avg_yield_rate",
            "average_yield",
            "avg_yield",
            "line_average_yield_rate",
            "product_line_average_yield_rate",
        ],
    )

    if current_yield_rate is None:
        data_quality_notes.append(
            "current_yield_rate 계열 컬럼을 찾지 못해 "
            "현재 라인 수율 기반 LOW_YIELD 판단이 제한됩니다."
        )

    if standard_yield_rate is None:
        data_quality_notes.append(
            "standard_yield_rate 계열 컬럼을 찾지 못해 표준 수율 대비 판단이 제한됩니다."
        )

    if average_yield_rate is None:
        data_quality_notes.append(
            "average_yield_rate 계열 컬럼을 찾지 못해 평균 수율 대비 판단이 제한됩니다."
        )

    checks = []

    # Check 1. 현재 수율이 표준 수율보다 낮은가?
    if current_yield_rate is not None and standard_yield_rate is not None:
        gap = standard_yield_rate - current_yield_rate

        checks.append(
            {
                "check_name": "CURRENT_VS_STANDARD",
                "description": "현재 라인 수율이 제품-Line 표준 수율보다 낮은지 확인",
                "baseline_name": "표준 수율",
                "baseline_rate": standard_yield_rate,
                "target_name": "현재 라인 수율",
                "target_rate": current_yield_rate,
                "gap": gap,
                "threshold": YIELD_CONFIG.low_yield_gap_threshold,
                "triggered": gap >= YIELD_CONFIG.low_yield_gap_threshold,
                "evidence": (
                    f"현재 라인 수율은 {format_rate(current_yield_rate)}이고 "
                    f"표준 수율은 {format_rate(standard_yield_rate)}입니다. "
                    f"실제 차이는 {format_pp(gap)}이며, "
                    "LOW_YIELD 판단 기준 "
                    f"{format_pp(YIELD_CONFIG.low_yield_gap_threshold)}와 비교했습니다."
                ),
            }
        )

    # Check 2. 현재 수율이 평균 수율보다 낮은가?
    if current_yield_rate is not None and average_yield_rate is not None:
        gap = average_yield_rate - current_yield_rate

        checks.append(
            {
                "check_name": "CURRENT_VS_AVERAGE",
                "description": "현재 라인 수율이 평균 수율보다 낮은지 확인",
                "baseline_name": "평균 수율",
                "baseline_rate": average_yield_rate,
                "target_name": "현재 라인 수율",
                "target_rate": current_yield_rate,
                "gap": gap,
                "threshold": YIELD_CONFIG.low_yield_gap_threshold,
                "triggered": gap >= YIELD_CONFIG.low_yield_gap_threshold,
                "evidence": (
                    f"현재 라인 수율은 {format_rate(current_yield_rate)}이고 "
                    f"평균 수율은 {format_rate(average_yield_rate)}입니다. "
                    f"실제 차이는 {format_pp(gap)}이며, "
                    "LOW_YIELD 판단 기준 "
                    f"{format_pp(YIELD_CONFIG.low_yield_gap_threshold)}와 비교했습니다."
                ),
            }
        )

    # Check 3. 제품-Line 표준 수율 자체가 평균 수율보다 낮은가?
    # 이 경우는 현재 일시적 저하라기보다 해당 제품-Line 조합의 수율 리스크로 해석합니다.
    if standard_yield_rate is not None and average_yield_rate is not None:
        gap = average_yield_rate - standard_yield_rate

        checks.append(
            {
                "check_name": "STANDARD_VS_AVERAGE",
                "description": "제품-Line 표준 수율이 평균 수율보다 낮은지 확인",
                "baseline_name": "평균 수율",
                "baseline_rate": average_yield_rate,
                "target_name": "제품-Line 표준 수율",
                "target_rate": standard_yield_rate,
                "gap": gap,
                "threshold": YIELD_CONFIG.low_yield_gap_threshold,
                "triggered": gap >= YIELD_CONFIG.low_yield_gap_threshold,
                "evidence": format_yield_gap_sentence(
                    target_name="제품-Line 표준 수율",
                    target_rate=standard_yield_rate,
                    baseline_name="평균 수율",
                    baseline_rate=average_yield_rate,
                    threshold=YIELD_CONFIG.low_yield_gap_threshold,
                ),
            }
        )

    triggered_checks = [check for check in checks if check["triggered"]]
    max_gap = max([check["gap"] for check in triggered_checks], default=None)

    plan_or_order_qty = get_plan_or_order_quantity(order_df, plan_df)
    hourly_capacity = get_line_hourly_capacity(line_df, line_status_df)

    additional_required_qty = None
    additional_production_hours = None
    baseline_yield_rate_for_calc = None

    # 추가 생산량 계산은 current_yield_rate가 있을 때만 수행합니다.
    # 기준 수율은 standard_yield_rate를 우선 사용하고, 없으면 average_yield_rate를 사용합니다.
    if current_yield_rate is not None:
        if standard_yield_rate is not None and standard_yield_rate > current_yield_rate:
            baseline_yield_rate_for_calc = standard_yield_rate
        elif average_yield_rate is not None and average_yield_rate > current_yield_rate:
            baseline_yield_rate_for_calc = average_yield_rate

    if (
        current_yield_rate is not None
        and baseline_yield_rate_for_calc is not None
        and current_yield_rate >= YIELD_CONFIG.min_valid_yield_rate
        and baseline_yield_rate_for_calc >= YIELD_CONFIG.min_valid_yield_rate
        and plan_or_order_qty is not None
        and not pd.isna(plan_or_order_qty)
    ):
        required_total_at_baseline = plan_or_order_qty / baseline_yield_rate_for_calc
        required_total_at_current = plan_or_order_qty / current_yield_rate

        additional_required_qty = max(
            required_total_at_current - required_total_at_baseline,
            0.0,
        )

        if hourly_capacity is not None and hourly_capacity > 0:
            additional_production_hours = additional_required_qty / hourly_capacity

    if triggered_checks:
        severity = classify_yield_severity(max_gap)

        evidence = [check["evidence"] for check in triggered_checks]

        if additional_required_qty is not None:
            evidence.append(
                "현재 수율 기준 목표 수량 달성을 위해 약 "
                f"{format_qty_for_yield(additional_required_qty)}의 "
                "추가 생산량이 필요할 것으로 추정됩니다."
            )

        if additional_production_hours is not None:
            evidence.append(
                "라인 생산능력 기준 추가 생산 시간은 약 "
                f"{additional_production_hours:.1f}시간으로 추정됩니다."
            )

        cause_candidates.append(
            {
                "cause_type": "LOW_YIELD",
                "korean_name": "수율 저하",
                "priority_band": "CONTRIBUTOR",
                "severity": severity,
                "delay_contribution_hours": additional_production_hours,
                "rank_reason": (
                    "현재 라인 수율 또는 제품-Line 표준 수율이 기준 수율 대비 낮아 "
                    "계획 수량 달성에 추가 생산 시간이 필요할 수 있습니다."
                ),
                "evidence": evidence,
                "metrics": {
                    "current_yield_rate": current_yield_rate,
                    "current_yield_source": current_source,
                    "current_yield_col": current_col,
                    "standard_yield_rate": standard_yield_rate,
                    "standard_yield_source": standard_source,
                    "standard_yield_col": standard_col,
                    "average_yield_rate": average_yield_rate,
                    "average_yield_source": average_source,
                    "average_yield_col": average_col,
                    "max_yield_gap": max_gap,
                    "low_yield_gap_threshold": YIELD_CONFIG.low_yield_gap_threshold,
                    "high_yield_gap_threshold": YIELD_CONFIG.high_yield_gap_threshold,
                    "plan_or_order_qty": plan_or_order_qty,
                    "hourly_capacity": hourly_capacity,
                    "baseline_yield_rate_for_calc": baseline_yield_rate_for_calc,
                    "additional_required_qty": additional_required_qty,
                    "additional_production_hours": additional_production_hours,
                    "triggered_checks": triggered_checks,
                },
                "action_hint": (
                    "현재 라인 수율 저하 원인, 불량률 증가 여부, 라인 조건 조정, "
                    "생산량 보정 필요 여부를 확인합니다."
                ),
            }
        )

    detail = {
        "current_yield_rate": current_yield_rate,
        "current_yield_source": current_source,
        "current_yield_col": current_col,
        "standard_yield_rate": standard_yield_rate,
        "standard_yield_source": standard_source,
        "standard_yield_col": standard_col,
        "average_yield_rate": average_yield_rate,
        "average_yield_source": average_source,
        "average_yield_col": average_col,
        "checks": checks,
        "triggered_checks": triggered_checks,
        "low_yield_gap_threshold": YIELD_CONFIG.low_yield_gap_threshold,
        "high_yield_gap_threshold": YIELD_CONFIG.high_yield_gap_threshold,
        "plan_or_order_qty": plan_or_order_qty,
        "hourly_capacity": hourly_capacity,
        "baseline_yield_rate_for_calc": baseline_yield_rate_for_calc,
        "additional_required_qty": additional_required_qty,
        "additional_production_hours": additional_production_hours,
    }

    return {
        "analyzer": "YieldAnalyzer",
        "status": "COMPLETED",
        "cause_candidates": cause_candidates,
        "detail": detail,
        "data_quality": {
            "status": "OK" if not data_quality_notes else "PARTIAL",
            "notes": data_quality_notes,
        },
    }


print("Yield Analyzer 함수 정의 완료")

Yield Analyzer 함수 정의 완료

In [33]:
# Cell 33. Yield Analyzer 실행

yield_analysis = run_yield_analyzer(risk_context)

print("Yield Analyzer status:", yield_analysis["status"])
print("Data quality:", yield_analysis["data_quality"])

print("\n수율 상세 계산 결과")
display(
    pd.DataFrame(
        [
            {
                "current_yield_rate": yield_analysis["detail"]["current_yield_rate"],
                "current_yield_source": yield_analysis["detail"]["current_yield_source"],
                "current_yield_col": yield_analysis["detail"]["current_yield_col"],
                "standard_yield_rate": yield_analysis["detail"]["standard_yield_rate"],
                "standard_yield_source": yield_analysis["detail"]["standard_yield_source"],
                "standard_yield_col": yield_analysis["detail"]["standard_yield_col"],
                "average_yield_rate": yield_analysis["detail"]["average_yield_rate"],
                "average_yield_source": yield_analysis["detail"]["average_yield_source"],
                "average_yield_col": yield_analysis["detail"]["average_yield_col"],
                "low_yield_gap_threshold": yield_analysis["detail"]["low_yield_gap_threshold"],
                "high_yield_gap_threshold": yield_analysis["detail"]["high_yield_gap_threshold"],
                "plan_or_order_qty": yield_analysis["detail"]["plan_or_order_qty"],
                "hourly_capacity": yield_analysis["detail"]["hourly_capacity"],
                "baseline_yield_rate_for_calc": yield_analysis["detail"][
                    "baseline_yield_rate_for_calc"
                ],
                "additional_required_qty": yield_analysis["detail"]["additional_required_qty"],
                "additional_production_hours": yield_analysis["detail"][
                    "additional_production_hours"
                ],
            }
        ]
    )
)

print("\n수율 비교 체크 결과")
checks_df = pd.DataFrame(yield_analysis["detail"]["checks"])
display(checks_df)

print("\nLOW_YIELD 판단에 사용된 triggered checks")
triggered_checks_df = pd.DataFrame(yield_analysis["detail"]["triggered_checks"])
display(triggered_checks_df)

print("\n원인 후보 수:", len(yield_analysis["cause_candidates"]))

if yield_analysis["cause_candidates"]:
    for idx, candidate in enumerate(yield_analysis["cause_candidates"], start=1):
        print("\n" + "-" * 100)
        print(f"[Candidate {idx}] {candidate['cause_type']} / {candidate['korean_name']}")
        print("priority_band:", candidate["priority_band"])
        print("severity:", candidate["severity"])
        print("delay_contribution_hours:", candidate["delay_contribution_hours"])
        print("rank_reason:", candidate["rank_reason"])
        print("evidence:")
        for ev in candidate["evidence"]:
            print("-", ev)
else:
    print("Yield 관련 원인 후보가 없습니다.")

Yield Analyzer status: COMPLETED
Data quality: {'status': 'OK', 'notes': []}

수율 상세 계산 결과

,current_yield_rate,current_yield_source,current_yield_col,standard_yield_rate,standard_yield_source,standard_yield_col,average_yield_rate,average_yield_source,average_yield_col,low_yield_gap_threshold,high_yield_gap_threshold,plan_or_order_qty,hourly_capacity,baseline_yield_rate_for_calc,additional_required_qty,additional_production_hours
0,0.937,line_status,current_yield_rate,0.928,product_line_capability,standard_yield_rate,0.938,product,average_yield_rate,0.03,0.05,12800.0,625.0,0.938,14.56356,0.023302

수율 비교 체크 결과

,check_name,description,baseline_name,baseline_rate,target_name,target_rate,gap,threshold,triggered,evidence
0,CURRENT_VS_STANDARD,현재 라인 수율이 제품-Line 표준 수율보다 낮은지 확인,표준 수율,0.928,현재 라인 수율,0.937,-0.009,0.03,False,"현재 라인 수율은 93.7%이고 표준 수율은 92.8%입니다. 실제 차이는 -0.9%p이며, LOW_YIELD 판단 기준 3.0%p와 비교했습니다."
1,CURRENT_VS_AVERAGE,현재 라인 수율이 평균 수율보다 낮은지 확인,평균 수율,0.938,현재 라인 수율,0.937,0.001,0.03,False,"현재 라인 수율은 93.7%이고 평균 수율은 93.8%입니다. 실제 차이는 0.1%p이며, LOW_YIELD 판단 기준 3.0%p와 비교했습니다."
2,STANDARD_VS_AVERAGE,제품-Line 표준 수율이 평균 수율보다 낮은지 확인,평균 수율,0.938,제품-Line 표준 수율,0.928,0.010,0.03,False,제품-Line 표준 수율은 92.8%이고 평균 수율은 93.8%입니다. 제품-Line 표준 수율이 평균 수율보다 1.0%p 낮지만 LOW_YIELD 판단 기준 3.0%p에는 미달합니다.

LOW_YIELD 판단에 사용된 triggered checks

Empty DataFrame
Columns: []
Index: []

원인 후보 수: 0
Yield 관련 원인 후보가 없습니다.

## Machine Analyzer Node

In [34]:
# Cell 35. Machine 관련 데이터 확인

machine_context_keys = [
    "machines",
    "machine_statuses",
    "plan",
    "line",
]

for key in machine_context_keys:
    df = risk_context["tables"].get(key)

    print("\n" + "=" * 100)
    print(f"[{key}] shape={df.shape if isinstance(df, pd.DataFrame) else None}")

    if isinstance(df, pd.DataFrame) and not df.empty:
        print("columns:")
        print(list(df.columns))
        display(df.head(20))
    else:
        print("데이터 없음")

====================================================================================================
[machines] shape=(5, 8)
columns:
['machine_id', 'line_id', 'machine_code', 'machine_name', 'machine_type', 'machine_role', 'machine_order', 'updated_at']

,machine_id,line_id,machine_code,machine_name,machine_type,machine_role,machine_order,updated_at
0,6,2,M-ABS02-FEED,ABS-02 원료 투입기,FEEDER,ABS 계열 원료 투입 및 계량,1,2026-03-31 15:00:00+00:00
1,7,2,M-ABS02-MIX,ABS-02 컴파운딩 믹서,MIXER,ABS 수지·고무·첨가제 혼합,2,2026-03-31 15:00:00+00:00
2,8,2,M-ABS02-EXT,ABS-02 압출기,EXTRUDER,ABS 컴파운드 압출 및 성형,3,2026-03-31 15:00:00+00:00
3,9,2,M-ABS02-COOL,ABS-02 냉각 절단기,COOLER,압출물 냉각 및 절단,4,2026-03-31 15:00:00+00:00
4,10,2,M-ABS02-PACK,ABS-02 검사 포장기,PACKER,품질 검사 및 포장,5,2026-03-31 15:00:00+00:00

====================================================================================================
[machine_statuses] shape=(5, 11)
columns:
['machine_status_id', 'machine_id', 'line_id', 'plan_id', 'product_id', 'recorded_at', 'operation_status', 'processed_quantity', 'defect_quantity', 'status_note', 'updated_at']

,machine_status_id,machine_id,line_id,plan_id,product_id,recorded_at,operation_status,processed_quantity,defect_quantity,status_note,updated_at
0,6,6,2,401,1,2026-06-01 00:00:00+00:00,RUNNING,9894,90,라인 생산계획에 따라 정상 가동 중,2026-06-01 00:00:00+00:00
1,7,7,2,401,1,2026-06-01 00:00:00+00:00,RUNNING,9703,210,라인 생산계획에 따라 정상 가동 중,2026-06-01 00:00:00+00:00
2,8,8,2,401,1,2026-06-01 00:00:00+00:00,RUNNING,9513,599,라인 생산계획에 따라 정상 가동 중,2026-06-01 00:00:00+00:00
3,9,9,2,401,1,2026-06-01 00:00:00+00:00,RUNNING,9323,389,라인 생산계획에 따라 정상 가동 중,2026-06-01 00:00:00+00:00
4,10,10,2,401,1,2026-06-01 00:00:00+00:00,RUNNING,9037,689,포장 대기 물량 증가로 처리량 모니터링 필요,2026-06-01 00:00:00+00:00

====================================================================================================
[plan] shape=(1, 14)
columns:
['plan_id', 'order_id', 'product_id', 'line_id', 'operator_id', 'planned_start_at', 'planned_end_at', 'estimated_duration_hr', 'planned_quantity', 'plan_sequence', 'plan_status', 'created_at', 'updated_at', 'is_current']

,plan_id,order_id,product_id,line_id,operator_id,planned_start_at,planned_end_at,estimated_duration_hr,planned_quantity,plan_sequence,plan_status,created_at,updated_at,is_current
0,424,397,2,2,6,2026-06-03 01:53:06+00:00,2026-06-04 05:11:06+00:00,21.0,12800,50,SCHEDULED,2026-05-23 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True

====================================================================================================
[line] shape=(1, 9)
columns:
['line_id', 'line_code', 'line_name', 'max_capacity_per_day', 'capacity_unit', 'supports_changeover', 'is_active', 'description', 'updated_at']

,line_id,line_code,line_name,max_capacity_per_day,capacity_unit,supports_changeover,is_active,description,updated_at
0,2,LINE-ABS-02,ABS 보조 생산 Line,15000,KG,True,True,ABS 계열 보조 생산 및 긴급 주문 대응을 위한 Batch 생산 Line,2026-03-31 15:00:00+00:00

In [35]:
# Cell 36. Machine Analyzer 설정값 및 유틸리티 정의

import json
from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd


@dataclass
class MachineAnalyzerConfig:
    # 즉시 비정상으로 판단할 설비 상태
    hard_abnormal_statuses: tuple = (
        "ERROR",
        "STOPPED",
        "FAULT",
        "DOWN",
    )

    # 점검 상태. 생산 예정 시간과 겹치거나 종료 시간이 없으면 이상 후보로 판단
    maintenance_statuses: tuple = (
        "MAINTENANCE",
        "MAINTENANCE_IN_PROGRESS",
        "INSPECTION",
    )

    # 정상/가동 상태
    normal_statuses: tuple = (
        "NORMAL",
        "RUNNING",
        "ACTIVE",
        "AVAILABLE",
        "IDLE",
        "READY",
    )


MACHINE_CONFIG = MachineAnalyzerConfig()


def first_existing_col_local(df: pd.DataFrame, candidates: list[str]) -> str | None:
    if df is None or df.empty:
        return None

    cols = set(df.columns)
    for col in candidates:
        if col in cols:
            return col

    return None


def to_number_machine(value, default: float = np.nan) -> float:
    if value is None:
        return default

    try:
        if pd.isna(value):
            return default
    except TypeError:
        pass

    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def to_datetime_utc(value):
    if value is None:
        return None

    try:
        if pd.isna(value):
            return None
    except TypeError:
        pass

    try:
        dt = pd.to_datetime(value, utc=True, errors="coerce")
        if pd.isna(dt):
            return None
        return dt
    except Exception:
        return None


def hours_between_utc(later, earlier) -> float | None:
    later_dt = to_datetime_utc(later)
    earlier_dt = to_datetime_utc(earlier)

    if later_dt is None or earlier_dt is None:
        return None

    return (later_dt - earlier_dt).total_seconds() / 3600.0


def normalize_machine_status(value) -> str | None:
    if value is None:
        return None

    try:
        if pd.isna(value):
            return None
    except TypeError:
        pass

    return str(value).strip().upper()


def parse_bool(value) -> bool | None:
    if value is None:
        return None

    try:
        if pd.isna(value):
            return None
    except TypeError:
        pass

    if isinstance(value, bool):
        return value

    value_str = str(value).strip().upper()

    if value_str in {"TRUE", "T", "Y", "YES", "1"}:
        return True

    if value_str in {"FALSE", "F", "N", "NO", "0"}:
        return False

    return None


def format_machine_datetime(value) -> str:
    dt = to_datetime_utc(value)
    if dt is None:
        return "확인 필요"
    return dt.strftime("%Y-%m-%d %H:%M:%S UTC")


def time_range_overlaps(start_a, end_a, start_b, end_b) -> bool | None:
    """
    [start_a, end_a]와 [start_b, end_b]가 겹치는지 확인.
    하나라도 필요한 값이 없으면 None.
    """
    start_a = to_datetime_utc(start_a)
    end_a = to_datetime_utc(end_a)
    start_b = to_datetime_utc(start_b)
    end_b = to_datetime_utc(end_b)

    if start_a is None or end_a is None or start_b is None or end_b is None:
        return None

    return start_a <= end_b and start_b <= end_a


def choose_latest_status_rows(
    statuses_df: pd.DataFrame,
    machine_id_col: str,
    status_time_col: str | None,
) -> pd.DataFrame:
    """
    machine_id별 최신 상태 row 1개만 남깁니다.
    status_time_col이 없으면 원래 순서를 유지한 뒤 machine_id별 첫 row를 사용합니다.
    """
    if statuses_df.empty:
        return statuses_df

    df = statuses_df.copy()

    if status_time_col and status_time_col in df.columns:
        df["_status_time_sort"] = pd.to_datetime(df[status_time_col], utc=True, errors="coerce")
        df = df.sort_values("_status_time_sort", ascending=False)

    df = df.drop_duplicates(subset=[machine_id_col], keep="first")

    if "_status_time_sort" in df.columns:
        df = df.drop(columns=["_status_time_sort"])

    return df.reset_index(drop=True)


def format_machine_name(
    machine_row: pd.Series, machine_id, machine_name_col, machine_code_col
) -> str:
    machine_name = machine_row.get(machine_name_col) if machine_name_col else None
    machine_code = machine_row.get(machine_code_col) if machine_code_col else None

    if machine_code and machine_name:
        return f"{machine_code}({machine_name})"

    if machine_name:
        return str(machine_name)

    if machine_code:
        return str(machine_code)

    return f"machine_id={machine_id}"

In [36]:
# Cell 37. Machine Analyzer 컬럼 매핑

machines_df = risk_context["tables"]["machines"].copy()
machine_statuses_df = risk_context["tables"]["machine_statuses"].copy()
plan_df = risk_context["tables"]["plan"].copy()
line_df = risk_context["tables"]["line"].copy()

if machines_df.empty:
    raise RuntimeError("machines 데이터가 없습니다. Machine Analyzer를 실행할 수 없습니다.")

if machine_statuses_df.empty:
    raise RuntimeError("machine_statuses 데이터가 없습니다. Machine Analyzer를 실행할 수 없습니다.")


machine_id_col = first_existing_col_local(machines_df, ["machine_id", "id", "equipment_id"])

machine_line_id_col = first_existing_col_local(machines_df, ["line_id", "production_line_id"])

machine_name_col = first_existing_col_local(machines_df, ["machine_name", "name", "equipment_name"])

machine_code_col = first_existing_col_local(machines_df, ["machine_code", "code", "equipment_code"])

machine_is_critical_col = first_existing_col_local(
    machines_df, ["is_critical", "critical_yn", "is_core", "core_machine"]
)


status_machine_id_col = first_existing_col_local(
    machine_statuses_df, ["machine_id", "id", "equipment_id"]
)

machine_status_col = first_existing_col_local(
    machine_statuses_df,
    [
        "machine_status",
        "status",
        "operation_status",
        "state",
        "status_type",
        "current_status",
    ],
)

status_time_col = first_existing_col_local(
    machine_statuses_df,
    [
        "recorded_at",
        "updated_at",
        "created_at",
        "status_at",
        "checked_at",
        "measured_at",
    ],
)

recovery_expected_at_col = first_existing_col_local(
    machine_statuses_df,
    [
        "expected_recovery_at",
        "recovery_expected_at",
        "estimated_recovery_at",
        "recovery_at",
        "expected_restore_at",
    ],
)

maintenance_start_at_col = first_existing_col_local(
    machine_statuses_df,
    [
        "maintenance_start_at",
        "inspection_start_at",
        "scheduled_maintenance_start_at",
        "started_at",
    ],
)

maintenance_end_at_col = first_existing_col_local(
    machine_statuses_df,
    [
        "maintenance_end_at",
        "inspection_end_at",
        "scheduled_maintenance_end_at",
        "expected_maintenance_end_at",
        "ended_at",
    ],
)

plan_start_col = first_existing_col_local(
    plan_df,
    [
        "planned_start_at",
        "start_at",
        "scheduled_start_at",
        "production_start_at",
    ],
)

plan_end_col = first_existing_col_local(
    plan_df,
    [
        "planned_end_at",
        "end_at",
        "scheduled_end_at",
        "production_end_at",
    ],
)


required_mapping = {
    "machine_id_col": machine_id_col,
    "status_machine_id_col": status_machine_id_col,
    "machine_status_col": machine_status_col,
}

missing_required = [k for k, v in required_mapping.items() if v is None]

if missing_required:
    print("Machine Analyzer 필수 컬럼 매핑 실패:", missing_required)
    print("machines columns:", list(machines_df.columns))
    print("machine_statuses columns:", list(machine_statuses_df.columns))
    raise RuntimeError("Machine Analyzer 필수 컬럼을 찾지 못했습니다. 실제 컬럼명을 확인해주세요.")


machine_mapping_result = {
    "machine_id_col": machine_id_col,
    "machine_line_id_col": machine_line_id_col,
    "machine_name_col": machine_name_col,
    "machine_code_col": machine_code_col,
    "machine_is_critical_col": machine_is_critical_col,
    "status_machine_id_col": status_machine_id_col,
    "machine_status_col": machine_status_col,
    "status_time_col": status_time_col,
    "recovery_expected_at_col": recovery_expected_at_col,
    "maintenance_start_at_col": maintenance_start_at_col,
    "maintenance_end_at_col": maintenance_end_at_col,
    "plan_start_col": plan_start_col,
    "plan_end_col": plan_end_col,
}

print("Machine Analyzer 컬럼 매핑 결과")
machine_mapping_result

Machine Analyzer 컬럼 매핑 결과

{'machine_id_col': 'machine_id',
 'machine_line_id_col': 'line_id',
 'machine_name_col': 'machine_name',
 'machine_code_col': 'machine_code',
 'machine_is_critical_col': None,
 'status_machine_id_col': 'machine_id',
 'machine_status_col': 'operation_status',
 'status_time_col': 'recorded_at',
 'recovery_expected_at_col': None,
 'maintenance_start_at_col': None,
 'maintenance_end_at_col': None,
 'plan_start_col': 'planned_start_at',
 'plan_end_col': 'planned_end_at'}

In [37]:
# Cell 38. Machine Analyzer 함수 정의 수정본


def run_machine_analyzer(risk_context: dict[str, Any]) -> dict[str, Any]:
    machines_df = risk_context["tables"]["machines"].copy()
    machine_statuses_df = risk_context["tables"]["machine_statuses"].copy()
    plan_df = risk_context["tables"]["plan"].copy()

    target_line_id = risk_context["ids"].get("line_id")

    cause_candidates = []
    data_quality_notes = []
    info_notes = []
    detail_rows = []

    planned_start_at = None
    planned_end_at = None

    if not plan_df.empty and plan_start_col:
        planned_start_at = plan_df.iloc[0].get(plan_start_col)

    if not plan_df.empty and plan_end_col:
        planned_end_at = plan_df.iloc[0].get(plan_end_col)

    # 현재 line에 연결된 설비만 필터링
    target_machines_df = machines_df.copy()

    if target_line_id is not None and machine_line_id_col:
        target_machines_df = target_machines_df[
            target_machines_df[machine_line_id_col] == target_line_id
        ].copy()

    if target_machines_df.empty:
        data_quality_notes.append(f"line_id={target_line_id}에 연결된 설비를 찾지 못했습니다.")

    latest_status_df = choose_latest_status_rows(
        statuses_df=machine_statuses_df,
        machine_id_col=status_machine_id_col,
        status_time_col=status_time_col,
    )

    status_by_machine_id = {
        row[status_machine_id_col]: row for _, row in latest_status_df.iterrows()
    }

    missing_status_machine_ids = []
    unhandled_status_values = set()

    hard_abnormal_detected = False
    maintenance_status_detected = False

    for _, machine_row in target_machines_df.iterrows():
        machine_id = machine_row.get(machine_id_col)

        machine_display_name = format_machine_name(
            machine_row=machine_row,
            machine_id=machine_id,
            machine_name_col=machine_name_col,
            machine_code_col=machine_code_col,
        )

        machine_line_id = (
            machine_row.get(machine_line_id_col) if machine_line_id_col else target_line_id
        )

        is_critical = (
            parse_bool(machine_row.get(machine_is_critical_col))
            if machine_is_critical_col
            else None
        )

        status_row = status_by_machine_id.get(machine_id)

        if status_row is None:
            missing_status_machine_ids.append(machine_id)

            detail_rows.append(
                {
                    "machine_id": machine_id,
                    "machine_name": machine_display_name,
                    "line_id": machine_line_id,
                    "machine_status": None,
                    "is_critical": is_critical,
                    "status_recorded_at": None,
                    "recovery_expected_at": None,
                    "maintenance_start_at": None,
                    "maintenance_end_at": None,
                    "is_abnormal": False,
                    "abnormal_reason": "status_missing",
                    "severity": None,
                    "priority_band": None,
                    "delay_contribution_hours": None,
                }
            )
            continue

        raw_status = status_row.get(machine_status_col)
        machine_status = normalize_machine_status(raw_status)

        recovery_expected_at = (
            status_row.get(recovery_expected_at_col) if recovery_expected_at_col else None
        )

        maintenance_start_at = (
            status_row.get(maintenance_start_at_col) if maintenance_start_at_col else None
        )

        maintenance_end_at = (
            status_row.get(maintenance_end_at_col) if maintenance_end_at_col else None
        )

        status_recorded_at = status_row.get(status_time_col) if status_time_col else None

        is_abnormal = False
        severity = "LOW"
        priority_band = None
        rank_reason = None
        abnormal_reason = None
        delay_contribution_hours = None
        evidence = []

        # 1. ERROR / STOPPED / FAULT / DOWN
        if machine_status in MACHINE_CONFIG.hard_abnormal_statuses:
            hard_abnormal_detected = True

            is_abnormal = True
            severity = "HIGH"
            priority_band = "BLOCKER"
            abnormal_reason = "hard_abnormal_status"
            rank_reason = (
                "현재 주문이 배정된 라인의 설비가 비정상 상태로 생산 진행이 제한될 수 있습니다."
            )

            evidence.append(f"{machine_display_name} 상태가 {machine_status}입니다.")

            if recovery_expected_at is not None and planned_start_at is not None:
                recovery_delay_hours = hours_between_utc(
                    recovery_expected_at,
                    planned_start_at,
                )

                if recovery_delay_hours is not None and recovery_delay_hours > 0:
                    delay_contribution_hours = recovery_delay_hours

        # 2. MAINTENANCE / INSPECTION
        elif machine_status in MACHINE_CONFIG.maintenance_statuses:
            maintenance_status_detected = True

            # 점검 시간 컬럼이 없으면 현재 점검 상태 자체를 후보로 본다.
            if maintenance_start_at_col is None or maintenance_end_at_col is None:
                is_abnormal = True
                severity = "HIGH"
                priority_band = "BLOCKER"
                abnormal_reason = "maintenance_status_without_time_columns"
                rank_reason = (
                    "설비가 점검 상태이나 점검 시작/종료 시각 정보가 없어 "
                    "생산 가능 시점 확인이 필요합니다."
                )
                evidence.append(
                    f"{machine_display_name} 상태가 {machine_status}이며, "
                    "점검 시간 정보가 확인되지 않습니다."
                )

            else:
                overlap = time_range_overlaps(
                    maintenance_start_at,
                    maintenance_end_at,
                    planned_start_at,
                    planned_end_at,
                )

                maintenance_end_delay_hours = hours_between_utc(
                    maintenance_end_at,
                    planned_start_at,
                )

                if overlap is True:
                    is_abnormal = True
                    severity = "HIGH"
                    priority_band = "BLOCKER"
                    abnormal_reason = "maintenance_overlaps_plan"
                    rank_reason = (
                        "설비 점검 시간이 계획 생산 시간과 겹쳐 생산 진행이 제한될 수 있습니다."
                    )
                    evidence.append(
                        f"{machine_display_name} 상태가 {machine_status}이며, "
                        "점검 시간이 계획 생산 시간과 겹칩니다."
                    )

                elif maintenance_end_delay_hours is not None and maintenance_end_delay_hours > 0:
                    is_abnormal = True
                    severity = "MEDIUM"
                    priority_band = "TIME_CRITICAL"
                    abnormal_reason = "maintenance_ends_after_plan_start"
                    rank_reason = (
                        "설비 점검 종료 시각이 계획 생산 시작 시각보다 늦어 "
                        "생산 시작이 지연될 수 있습니다."
                    )
                    delay_contribution_hours = maintenance_end_delay_hours
                    evidence.append(
                        f"{machine_display_name} 상태가 {machine_status}이며, "
                        f"점검 종료 예정 시각이 계획 시작보다 약 "
                        f"{maintenance_end_delay_hours:.1f}시간 늦습니다."
                    )

                else:
                    is_abnormal = False
                    severity = "LOW"
                    abnormal_reason = "maintenance_not_overlapping_plan"

        # 3. 정상 상태
        elif machine_status in MACHINE_CONFIG.normal_statuses:
            is_abnormal = False
            severity = "LOW"
            abnormal_reason = "normal_status"

        # 4. 알 수 없는 상태
        else:
            is_abnormal = False
            severity = "LOW"
            abnormal_reason = "unhandled_status"
            if machine_status is not None:
                unhandled_status_values.add(machine_status)

        if is_abnormal:
            if machine_line_id is not None:
                evidence.append(
                    f"해당 설비는 현재 배정 라인 {machine_line_id}에 연결되어 있습니다."
                )

            if is_critical is True:
                evidence.append("해당 설비는 핵심 설비로 표시되어 있습니다.")
            elif is_critical is False:
                evidence.append("해당 설비는 핵심 설비로 표시되어 있지는 않습니다.")

            if recovery_expected_at is not None:
                evidence.append(
                    f"복구 예정 시각은 {format_machine_datetime(recovery_expected_at)}입니다."
                )

            if maintenance_start_at is not None or maintenance_end_at is not None:
                evidence.append(
                    f"점검 시간 범위는 "
                    f"{format_machine_datetime(maintenance_start_at)} ~ "
                    f"{format_machine_datetime(maintenance_end_at)}입니다."
                )

            if delay_contribution_hours is not None:
                evidence.append(
                    f"설비 상태로 인한 예상 지연 기여시간은 "
                    f"약 {delay_contribution_hours:.1f}시간으로 추정됩니다."
                )
            else:
                evidence.append(
                    "복구 또는 점검 종료 예정 시각 정보가 부족하여 "
                    "설비 이상으로 인한 정확한 지연 기여시간은 계산하지 않았습니다."
                )

            cause_candidates.append(
                {
                    "cause_type": "MACHINE_ABNORMAL",
                    "korean_name": "설비 상태 이상",
                    "priority_band": priority_band or "BLOCKER",
                    "severity": severity or "HIGH",
                    "delay_contribution_hours": delay_contribution_hours,
                    "rank_reason": rank_reason
                    or (
                        "현재 주문이 배정된 라인의 설비 상태 이상으로 "
                        "생산 진행이 제한될 수 있습니다."
                    ),
                    "evidence": evidence,
                    "metrics": {
                        "machine_id": machine_id,
                        "machine_name": machine_display_name,
                        "line_id": machine_line_id,
                        "machine_status": machine_status,
                        "is_critical": is_critical,
                        "abnormal_reason": abnormal_reason,
                        "recovery_expected_at": str(recovery_expected_at),
                        "maintenance_start_at": str(maintenance_start_at),
                        "maintenance_end_at": str(maintenance_end_at),
                        "delay_contribution_hours": delay_contribution_hours,
                    },
                    "action_hint": (
                        "설비 복구 예상 시각을 확인하고, 대체 설비 또는 "
                        "대체 라인 사용 가능 여부를 검토합니다."
                    ),
                }
            )

        detail_rows.append(
            {
                "machine_id": machine_id,
                "machine_name": machine_display_name,
                "line_id": machine_line_id,
                "machine_status": machine_status,
                "is_critical": is_critical,
                "status_recorded_at": status_recorded_at,
                "recovery_expected_at": recovery_expected_at,
                "maintenance_start_at": maintenance_start_at,
                "maintenance_end_at": maintenance_end_at,
                "is_abnormal": is_abnormal,
                "abnormal_reason": abnormal_reason,
                "severity": severity,
                "priority_band": priority_band,
                "delay_contribution_hours": delay_contribution_hours,
            }
        )

    # 상태 정보 누락은 실제 품질 문제
    if missing_status_machine_ids:
        data_quality_notes.append(
            f"machine_statuses에서 상태 정보를 찾지 못한 설비가 있습니다: "
            f"{missing_status_machine_ids}"
        )

    # 복구 예정 시각 컬럼은 hard abnormal이 있을 때만 필요
    if hard_abnormal_detected and recovery_expected_at_col is None:
        data_quality_notes.append(
            "비정상 설비가 있으나 복구 예정 시각 컬럼을 찾지 못해 "
            "설비 이상 지연 기여시간 계산이 제한됩니다."
        )

    # 점검 시간 컬럼은 MAINTENANCE 상태가 있을 때만 필요
    if maintenance_status_detected and (
        maintenance_start_at_col is None or maintenance_end_at_col is None
    ):
        data_quality_notes.append(
            "점검 상태 설비가 있으나 점검 시작/종료 시각 컬럼을 찾지 못해 "
            "MAINTENANCE와 생산 시간 겹침 판단이 제한됩니다."
        )

    if unhandled_status_values:
        data_quality_notes.append(
            f"정상/비정상 규칙에 포함되지 않은 설비 상태가 있습니다: "
            f"{sorted(unhandled_status_values)}"
        )

    detail_df = pd.DataFrame(detail_rows)

    if not cause_candidates and not data_quality_notes:
        info_notes.append(
            f"분석 대상 라인 설비 {len(detail_df)}대가 모두 정상 상태로 확인되어 "
            "MACHINE_ABNORMAL 후보를 생성하지 않았습니다."
        )

    return {
        "analyzer": "MachineAnalyzer",
        "status": "COMPLETED",
        "cause_candidates": cause_candidates,
        "detail_df": detail_df,
        "analysis_note": info_notes,
        "data_quality": {
            "status": "OK" if not data_quality_notes else "PARTIAL",
            "notes": data_quality_notes,
        },
        "column_mapping": machine_mapping_result,
    }


print("Machine Analyzer 함수 정의 완료")

Machine Analyzer 함수 정의 완료

In [38]:
# Cell 39. Machine Analyzer 실행 수정본

machine_analysis = run_machine_analyzer(risk_context)

print("Machine Analyzer status:", machine_analysis["status"])
print("Data quality:", machine_analysis["data_quality"])

print("\nAnalysis note:")
for note in machine_analysis.get("analysis_note", []):
    print("-", note)

print("\n설비 상태 상세 계산 결과")
display(machine_analysis["detail_df"])

print("\n원인 후보 수:", len(machine_analysis["cause_candidates"]))

if machine_analysis["cause_candidates"]:
    for idx, candidate in enumerate(machine_analysis["cause_candidates"], start=1):
        print("\n" + "-" * 100)
        print(f"[Candidate {idx}] {candidate['cause_type']} / {candidate['korean_name']}")
        print("priority_band:", candidate["priority_band"])
        print("severity:", candidate["severity"])
        print("delay_contribution_hours:", candidate["delay_contribution_hours"])
        print("rank_reason:", candidate["rank_reason"])
        print("evidence:")
        for ev in candidate["evidence"]:
            print("-", ev)
else:
    print("Machine 관련 원인 후보가 없습니다.")

Machine Analyzer status: COMPLETED
Data quality: {'status': 'OK', 'notes': []}

Analysis note:
- 분석 대상 라인 설비 5대가 모두 정상 상태로 확인되어 MACHINE_ABNORMAL 후보를 생성하지 않았습니다.

설비 상태 상세 계산 결과

,machine_id,machine_name,line_id,machine_status,is_critical,status_recorded_at,recovery_expected_at,maintenance_start_at,maintenance_end_at,is_abnormal,abnormal_reason,severity,priority_band,delay_contribution_hours
0,6,M-ABS02-FEED(ABS-02 원료 투입기),2,RUNNING,None,2026-06-01 00:00:00+00:00,None,None,None,False,normal_status,LOW,None,None
1,7,M-ABS02-MIX(ABS-02 컴파운딩 믹서),2,RUNNING,None,2026-06-01 00:00:00+00:00,None,None,None,False,normal_status,LOW,None,None
2,8,M-ABS02-EXT(ABS-02 압출기),2,RUNNING,None,2026-06-01 00:00:00+00:00,None,None,None,False,normal_status,LOW,None,None
3,9,M-ABS02-COOL(ABS-02 냉각 절단기),2,RUNNING,None,2026-06-01 00:00:00+00:00,None,None,None,False,normal_status,LOW,None,None
4,10,M-ABS02-PACK(ABS-02 검사 포장기),2,RUNNING,None,2026-06-01 00:00:00+00:00,None,None,None,False,normal_status,LOW,None,None

원인 후보 수: 0
Machine 관련 원인 후보가 없습니다.

In [39]:
# Cell 40. Machine Analyzer 결과 저장 수정본

if "analyzer_results" not in risk_context:
    risk_context["analyzer_results"] = {}

risk_context["analyzer_results"]["machine"] = {
    "analyzer": machine_analysis["analyzer"],
    "status": machine_analysis["status"],
    "cause_candidates": machine_analysis["cause_candidates"],
    "analysis_note": machine_analysis.get("analysis_note", []),
    "data_quality": machine_analysis["data_quality"],
}

machine_analysis_for_next_node = risk_context["analyzer_results"]["machine"]

print(
    json.dumps(
        machine_analysis_for_next_node,
        ensure_ascii=False,
        indent=2,
        default=str,
    )
)

{
  "analyzer": "MachineAnalyzer",
  "status": "COMPLETED",
  "cause_candidates": [],
  "analysis_note": [
    "분석 대상 라인 설비 5대가 모두 정상 상태로 확인되어 MACHINE_ABNORMAL 후보를 생성하지 않았습니다."
  ],
  "data_quality": {
    "status": "OK",
    "notes": []
  }
}

## Line Node

In [40]:
# Cell 41. 같은 라인 주변 생산계획 조회

import json
from typing import Any

import numpy as np
import pandas as pd


def first_existing_col_line(df: pd.DataFrame, candidates: list[str]) -> str | None:
    if df is None or df.empty:
        return None

    cols = set(df.columns)
    for col in candidates:
        if col in cols:
            return col

    return None


def get_same_line_plans_for_context(
    risk_context: dict[str, Any],
    limit: int = 100,
) -> pd.DataFrame:
    """
    같은 line_id에 배정된 생산계획을 조회합니다.
    선행/후행 작업, 일정 충돌, 생산 순서 제약 판단에 사용합니다.
    """
    if not has_table("production_plans"):
        print("production_plans 테이블이 없습니다.")
        return pd.DataFrame()

    line_id = risk_context["ids"].get("line_id")
    if line_id is None:
        print("line_id가 없어 같은 라인 생산계획을 조회하지 않습니다.")
        return pd.DataFrame()

    production_plan_cols = TABLE_COLUMNS.get("production_plans", [])

    line_col = None
    for candidate in ["line_id", "production_line_id", "assigned_line_id"]:
        if candidate in production_plan_cols:
            line_col = candidate
            break

    if line_col is None:
        print("production_plans에서 line_id 계열 컬럼을 찾지 못했습니다.")
        return pd.DataFrame()

    order_col = None
    for candidate in [
        "planned_start_at",
        "scheduled_start_at",
        "start_at",
        "production_start_at",
        "created_at",
        "plan_id",
    ]:
        if candidate in production_plan_cols:
            order_col = candidate
            break

    sql = f"""
        SELECT *
        FROM {tref_by_key("production_plans")}
        WHERE {q(line_col)} = :line_id
    """

    if order_col:
        sql += f"\nORDER BY {q(order_col)} ASC"

    sql += "\nLIMIT :limit"

    return read_df(
        sql,
        {
            "line_id": line_id,
            "limit": limit,
        },
    )


same_line_plans_df = get_same_line_plans_for_context(
    risk_context=risk_context,
    limit=100,
)

risk_context["tables"]["same_line_plans"] = same_line_plans_df

print("same_line_plans_df:", same_line_plans_df.shape)
display(same_line_plans_df.head(30))

same_line_plans_df: (52, 14)

,plan_id,order_id,product_id,line_id,operator_id,planned_start_at,planned_end_at,estimated_duration_hr,planned_quantity,plan_sequence,plan_status,created_at,updated_at,is_current
0,4,5,3,2,6,2025-06-25 22:10:47+00:00,2025-06-26 14:59:59+00:00,17.60,10300,1,COMPLETED,2025-06-09 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
1,7,32,2,2,6,2025-06-26 16:41:59+00:00,2025-06-28 10:12:35+00:00,27.00,16800,2,COMPLETED,2025-06-11 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
2,12,15,2,2,6,2025-07-03 13:43:47+00:00,2025-07-04 14:59:59+00:00,21.00,12400,3,COMPLETED,2025-06-16 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
3,16,14,3,2,7,2025-07-04 16:32:59+00:00,2025-07-05 09:49:47+00:00,19.20,10600,4,COMPLETED,2025-06-19 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
4,17,7,3,2,7,2025-07-06 07:25:47+00:00,2025-07-07 14:59:59+00:00,32.00,18300,5,COMPLETED,2025-06-19 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
5,31,13,2,2,7,2025-07-15 01:03:35+00:00,2025-07-15 14:59:59+00:00,12.00,6800,6,COMPLETED,2025-06-25 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
6,37,58,1,2,7,2025-07-15 16:23:59+00:00,2025-07-17 13:55:11+00:00,39.76,25700,7,COMPLETED,2025-07-01 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
7,46,61,2,2,7,2025-07-24 17:47:52+00:00,2025-07-26 02:26:16+00:00,22.50,13700,8,COMPLETED,2025-07-10 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
8,52,46,1,2,7,2025-08-06 14:09:35+00:00,2025-08-07 14:59:59+00:00,21.30,14200,9,COMPLETED,2025-07-14 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
9,62,43,3,2,7,2025-08-20 09:01:47+00:00,2025-08-21 14:59:59+00:00,32.00,18600,10,COMPLETED,2025-07-26 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
10,64,66,2,2,6,2025-08-21 16:41:59+00:00,2025-08-23 20:53:59+00:00,31.50,19100,11,COMPLETED,2025-07-29 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
11,70,64,2,2,7,2025-08-23 20:53:59+00:00,2025-08-25 18:37:47+00:00,30.00,18600,12,COMPLETED,2025-07-31 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
12,85,70,1,2,6,2025-09-06 15:56:23+00:00,2025-09-07 14:59:59+00:00,18.46,12100,13,COMPLETED,2025-08-10 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
13,102,99,1,2,6,2025-09-17 12:04:11+00:00,2025-09-19 02:59:59+00:00,31.24,20500,14,COMPLETED,2025-08-28 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
14,115,126,3,2,6,2025-09-19 04:11:59+00:00,2025-09-20 14:20:59+00:00,36.80,21100,15,COMPLETED,2025-09-05 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
15,116,115,3,2,7,2025-10-04 03:46:47+00:00,2025-10-05 14:59:59+00:00,36.80,21800,16,COMPLETED,2025-09-05 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
16,130,127,2,2,7,2025-10-05 16:41:59+00:00,2025-10-07 14:10:11+00:00,30.00,18600,17,COMPLETED,2025-09-14 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
17,138,114,2,2,6,2025-10-07 14:10:11+00:00,2025-10-08 07:29:23+00:00,13.50,7800,18,COMPLETED,2025-09-22 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
18,141,119,1,2,7,2025-10-22 18:20:23+00:00,2025-10-23 14:59:59+00:00,18.46,11500,19,COMPLETED,2025-09-23 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
19,154,148,3,2,6,2025-10-23 16:11:59+00:00,2025-10-25 02:16:11+00:00,32.00,18900,20,COMPLETED,2025-10-08 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
20,164,157,2,2,6,2025-11-06 13:19:11+00:00,2025-11-07 02:59:59+00:00,12.00,7100,21,COMPLETED,2025-10-14 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
21,170,141,1,2,7,2025-11-14 03:28:11+00:00,2025-11-15 14:59:59+00:00,31.24,20700,22,COMPLETED,2025-10-22 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
22,171,162,2,2,6,2025-11-15 16:59:59+00:00,2025-11-17 06:23:23+00:00,25.50,15400,23,COMPLETED,2025-10-26 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
23,188,176,2,2,7,2025-11-30 09:17:59+00:00,2025-12-01 14:59:59+00:00,24.00,14200,24,COMPLETED,2025-11-11 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
24,191,184,1,2,7,2025-12-10 07:27:35+00:00,2025-12-12 02:59:59+00:00,36.92,24400,25,COMPLETED,2025-11-13 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
25,211,208,2,2,7,2025-12-19 22:21:58+00:00,2025-12-21 17:08:10+00:00,31.50,19600,26,COMPLETED,2025-12-05 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
26,215,216,2,2,7,2025-12-21 17:08:10+00:00,2025-12-22 07:02:10+00:00,12.00,7100,27,COMPLETED,2025-12-08 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
27,226,212,1,2,6,2025-12-26 04:54:35+00:00,2025-12-27 14:59:59+00:00,28.40,18100,28,COMPLETED,2025-12-15 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
28,229,203,2,2,7,2026-01-03 14:27:35+00:00,2026-01-05 14:59:59+00:00,36.00,22300,29,COMPLETED,2025-12-17 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
29,234,206,1,2,7,2026-01-10 16:16:11+00:00,2026-01-12 02:59:59+00:00,29.82,19800,30,COMPLETED,2025-12-21 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True

In [41]:
# Cell 42. Line & Process 관련 데이터 확인

line_process_context_keys = [
    "plan",
    "line",
    "line_status",
    "product",
    "product_line_capability",
    "same_line_plans",
]

for key in line_process_context_keys:
    df = risk_context["tables"].get(key)

    print("\n" + "=" * 100)
    print(f"[{key}] shape={df.shape if isinstance(df, pd.DataFrame) else None}")

    if isinstance(df, pd.DataFrame) and not df.empty:
        print("columns:")
        print(list(df.columns))
        display(df.head(20))
    else:
        print("데이터 없음")

====================================================================================================
[plan] shape=(1, 14)
columns:
['plan_id', 'order_id', 'product_id', 'line_id', 'operator_id', 'planned_start_at', 'planned_end_at', 'estimated_duration_hr', 'planned_quantity', 'plan_sequence', 'plan_status', 'created_at', 'updated_at', 'is_current']

,plan_id,order_id,product_id,line_id,operator_id,planned_start_at,planned_end_at,estimated_duration_hr,planned_quantity,plan_sequence,plan_status,created_at,updated_at,is_current
0,424,397,2,2,6,2026-06-03 01:53:06+00:00,2026-06-04 05:11:06+00:00,21.0,12800,50,SCHEDULED,2026-05-23 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True

====================================================================================================
[line] shape=(1, 9)
columns:
['line_id', 'line_code', 'line_name', 'max_capacity_per_day', 'capacity_unit', 'supports_changeover', 'is_active', 'description', 'updated_at']

,line_id,line_code,line_name,max_capacity_per_day,capacity_unit,supports_changeover,is_active,description,updated_at
0,2,LINE-ABS-02,ABS 보조 생산 Line,15000,KG,True,True,ABS 계열 보조 생산 및 긴급 주문 대응을 위한 Batch 생산 Line,2026-03-31 15:00:00+00:00

====================================================================================================
[line_status] shape=(1, 15)
columns:
['line_status_id', 'line_id', 'product_id', 'plan_id', 'operator_id', 'recorded_at', 'operation_status', 'throughput_rate', 'current_yield_rate', 'waiting_quantity', 'waiting_time_hr', 'processed_quantity', 'defect_quantity', 'utilization_rate', 'progress_rate']

,line_status_id,line_id,product_id,plan_id,operator_id,recorded_at,operation_status,throughput_rate,current_yield_rate,waiting_quantity,waiting_time_hr,processed_quantity,defect_quantity,utilization_rate,progress_rate
0,2,2,1,401,7,2026-06-01 00:00:00+00:00,RUNNING,0.79,0.937,2100,1.7,9513,599,0.81,0.4686

====================================================================================================
[product] shape=(1, 9)
columns:
['product_id', 'product_code', 'product_name', 'product_category', 'unit', 'average_yield_rate', 'min_production_quantity', 'description', 'updated_at']

,product_id,product_code,product_name,product_category,unit,average_yield_rate,min_production_quantity,description,updated_at
0,2,ABS-WHT,ABS-WHITE,ABS,KG,0.938,1000,"WHITE 색상 ABS 컴파운드 제품, 색상 오염 관리 필요",2026-03-31 15:00:00+00:00

====================================================================================================
[product_line_capability] shape=(1, 8)
columns:
['product_line_id', 'product_id', 'line_id', 'standard_production_time_hr', 'capacity_per_day', 'standard_yield_rate', 'priority_rank', 'updated_at']

,product_line_id,product_id,line_id,standard_production_time_hr,capacity_per_day,standard_yield_rate,priority_rank,updated_at
0,4,2,2,1.92,12500,0.928,2,2026-03-31 15:00:00+00:00

====================================================================================================
[same_line_plans] shape=(52, 14)
columns:
['plan_id', 'order_id', 'product_id', 'line_id', 'operator_id', 'planned_start_at', 'planned_end_at', 'estimated_duration_hr', 'planned_quantity', 'plan_sequence', 'plan_status', 'created_at', 'updated_at', 'is_current']

,plan_id,order_id,product_id,line_id,operator_id,planned_start_at,planned_end_at,estimated_duration_hr,planned_quantity,plan_sequence,plan_status,created_at,updated_at,is_current
0,4,5,3,2,6,2025-06-25 22:10:47+00:00,2025-06-26 14:59:59+00:00,17.60,10300,1,COMPLETED,2025-06-09 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
1,7,32,2,2,6,2025-06-26 16:41:59+00:00,2025-06-28 10:12:35+00:00,27.00,16800,2,COMPLETED,2025-06-11 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
2,12,15,2,2,6,2025-07-03 13:43:47+00:00,2025-07-04 14:59:59+00:00,21.00,12400,3,COMPLETED,2025-06-16 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
3,16,14,3,2,7,2025-07-04 16:32:59+00:00,2025-07-05 09:49:47+00:00,19.20,10600,4,COMPLETED,2025-06-19 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
4,17,7,3,2,7,2025-07-06 07:25:47+00:00,2025-07-07 14:59:59+00:00,32.00,18300,5,COMPLETED,2025-06-19 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
5,31,13,2,2,7,2025-07-15 01:03:35+00:00,2025-07-15 14:59:59+00:00,12.00,6800,6,COMPLETED,2025-06-25 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
6,37,58,1,2,7,2025-07-15 16:23:59+00:00,2025-07-17 13:55:11+00:00,39.76,25700,7,COMPLETED,2025-07-01 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
7,46,61,2,2,7,2025-07-24 17:47:52+00:00,2025-07-26 02:26:16+00:00,22.50,13700,8,COMPLETED,2025-07-10 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
8,52,46,1,2,7,2025-08-06 14:09:35+00:00,2025-08-07 14:59:59+00:00,21.30,14200,9,COMPLETED,2025-07-14 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
9,62,43,3,2,7,2025-08-20 09:01:47+00:00,2025-08-21 14:59:59+00:00,32.00,18600,10,COMPLETED,2025-07-26 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
10,64,66,2,2,6,2025-08-21 16:41:59+00:00,2025-08-23 20:53:59+00:00,31.50,19100,11,COMPLETED,2025-07-29 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
11,70,64,2,2,7,2025-08-23 20:53:59+00:00,2025-08-25 18:37:47+00:00,30.00,18600,12,COMPLETED,2025-07-31 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
12,85,70,1,2,6,2025-09-06 15:56:23+00:00,2025-09-07 14:59:59+00:00,18.46,12100,13,COMPLETED,2025-08-10 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
13,102,99,1,2,6,2025-09-17 12:04:11+00:00,2025-09-19 02:59:59+00:00,31.24,20500,14,COMPLETED,2025-08-28 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
14,115,126,3,2,6,2025-09-19 04:11:59+00:00,2025-09-20 14:20:59+00:00,36.80,21100,15,COMPLETED,2025-09-05 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
15,116,115,3,2,7,2025-10-04 03:46:47+00:00,2025-10-05 14:59:59+00:00,36.80,21800,16,COMPLETED,2025-09-05 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
16,130,127,2,2,7,2025-10-05 16:41:59+00:00,2025-10-07 14:10:11+00:00,30.00,18600,17,COMPLETED,2025-09-14 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
17,138,114,2,2,6,2025-10-07 14:10:11+00:00,2025-10-08 07:29:23+00:00,13.50,7800,18,COMPLETED,2025-09-22 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
18,141,119,1,2,7,2025-10-22 18:20:23+00:00,2025-10-23 14:59:59+00:00,18.46,11500,19,COMPLETED,2025-09-23 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True
19,154,148,3,2,6,2025-10-23 16:11:59+00:00,2025-10-25 02:16:11+00:00,32.00,18900,20,COMPLETED,2025-10-08 00:00:00+00:00,2026-06-05 05:24:14.019548+00:00,True

In [42]:
# Cell 43. Line & Process Analyzer 설정값 및 유틸리티 정의

import json
from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd


@dataclass
class LineProcessAnalyzerConfig:
    # 라인 가동률 기준
    utilization_medium_threshold: float = 0.85
    utilization_high_threshold: float = 0.95

    # 처리량 비율 기준
    throughput_medium_threshold: float = 0.90
    throughput_high_threshold: float = 0.75

    # 대기시간 기준
    waiting_medium_hours: float = 4.0
    waiting_high_hours: float = 8.0

    # SETUP / CHANGEOVER 초과 시간 기준
    setup_overrun_medium_hours: float = 1.0
    setup_overrun_high_hours: float = 3.0
    changeover_overrun_medium_hours: float = 1.0
    changeover_overrun_high_hours: float = 3.0

    # 라인 상태 분류
    blocker_statuses: tuple = (
        "STOPPED",
        "DOWN",
        "FAULT",
        "ERROR",
        "MAINTENANCE",
    )

    flow_delay_statuses: tuple = (
        "SETUP",
        "CHANGEOVER",
        "WAITING",
        "QUEUED",
        "DELAYED",
        "OVERLOADED",
        "BOTTLENECK",
    )

    normal_statuses: tuple = (
        "RUNNING",
        "NORMAL",
        "ACTIVE",
        "AVAILABLE",
        "READY",
        "IDLE",
    )


LINE_CONFIG = LineProcessAnalyzerConfig()


def to_number_line(value, default: float = np.nan) -> float:
    if value is None:
        return default

    try:
        if pd.isna(value):
            return default
    except TypeError:
        pass

    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def to_datetime_line(value):
    if value is None:
        return None

    try:
        if pd.isna(value):
            return None
    except TypeError:
        pass

    try:
        dt = pd.to_datetime(value, utc=True, errors="coerce")
        if pd.isna(dt):
            return None
        return dt
    except Exception:
        return None


def hours_between_line(later, earlier) -> float | None:
    later_dt = to_datetime_line(later)
    earlier_dt = to_datetime_line(earlier)

    if later_dt is None or earlier_dt is None:
        return None

    return (later_dt - earlier_dt).total_seconds() / 3600.0


def normalize_ratio_line(value) -> float | None:
    """
    0.91 또는 91 모두 0.91로 정규화합니다.
    """
    if value is None:
        return None

    try:
        if pd.isna(value):
            return None
    except TypeError:
        pass

    try:
        v = float(value)
    except (TypeError, ValueError):
        return None

    if v < 0:
        return None

    if v > 1.0:
        v = v / 100.0

    return v


def normalize_status_line(value) -> str | None:
    if value is None:
        return None

    try:
        if pd.isna(value):
            return None
    except TypeError:
        pass

    return str(value).strip().upper()


def format_ratio_line(value: float | None) -> str:
    if value is None or pd.isna(value):
        return "확인 필요"
    return f"{value * 100:.1f}%"


def format_hours_line(value: float | None) -> str:
    if value is None or pd.isna(value):
        return "확인 필요"
    return f"{value:.1f}시간"


def get_duration_hours_from_row(
    row: pd.Series,
    hours_cols: list[str],
    minutes_cols: list[str],
) -> float | None:
    for col in hours_cols:
        if col in row.index:
            value = to_number_line(row.get(col), default=np.nan)
            if not pd.isna(value):
                return value

    for col in minutes_cols:
        if col in row.index:
            value = to_number_line(row.get(col), default=np.nan)
            if not pd.isna(value):
                return value / 60.0

    return None


def severity_by_threshold(
    value: float, medium_threshold: float, high_threshold: float, higher_is_worse: bool = True
) -> str:
    if value is None or pd.isna(value):
        return "UNKNOWN"

    if higher_is_worse:
        if value >= high_threshold:
            return "HIGH"
        if value >= medium_threshold:
            return "MEDIUM"
        return "LOW"

    # 낮을수록 나쁨
    if value <= high_threshold:
        return "HIGH"
    if value < medium_threshold:
        return "MEDIUM"
    return "LOW"


def max_severity(severities: list[str]) -> str:
    order = {
        "HIGH": 3,
        "MEDIUM": 2,
        "LOW": 1,
        "UNKNOWN": 0,
        None: 0,
    }

    if not severities:
        return "LOW"

    return max(severities, key=lambda s: order.get(s, 0))


def min_priority_band(bands: list[str]) -> str:
    order = {
        "BLOCKER": 1,
        "TIME_CRITICAL": 2,
        "FLOW_DELAY": 3,
        "CONTRIBUTOR": 4,
        None: 99,
    }

    if not bands:
        return "CONTRIBUTOR"

    return min(bands, key=lambda b: order.get(b, 99))


def build_line_signal(
    signal_type: str,
    priority_band: str,
    severity: str,
    evidence: str,
    rank_reason: str,
    delay_contribution_hours: float | None = None,
    metrics: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "signal_type": signal_type,
        "priority_band": priority_band,
        "severity": severity,
        "evidence": evidence,
        "rank_reason": rank_reason,
        "delay_contribution_hours": delay_contribution_hours,
        "metrics": metrics or {},
    }

In [43]:
# Cell 44. Line & Process Analyzer 컬럼 매핑

plan_df = risk_context["tables"]["plan"].copy()
line_df = risk_context["tables"]["line"].copy()
line_status_df = risk_context["tables"]["line_status"].copy()
product_df = risk_context["tables"]["product"].copy()
product_line_capability_df = (
    risk_context["tables"].get("product_line_capability", pd.DataFrame()).copy()
)
same_line_plans_df = risk_context["tables"].get("same_line_plans", pd.DataFrame()).copy()

# plan 컬럼
lp_plan_id_col = first_existing_col_line(plan_df, ["plan_id", "id"])

lp_plan_line_id_col = first_existing_col_line(
    plan_df, ["line_id", "production_line_id", "assigned_line_id"]
)

lp_plan_product_id_col = first_existing_col_line(plan_df, ["product_id"])

lp_plan_start_col = first_existing_col_line(
    plan_df, ["planned_start_at", "scheduled_start_at", "start_at", "production_start_at"]
)

lp_plan_end_col = first_existing_col_line(
    plan_df, ["planned_end_at", "scheduled_end_at", "end_at", "production_end_at"]
)

lp_plan_qty_col = first_existing_col_line(
    plan_df,
    ["planned_qty", "planned_quantity", "plan_qty", "quantity", "target_qty", "target_quantity"],
)

# line_status 컬럼
lp_line_status_col = first_existing_col_line(
    line_status_df, ["operation_status", "line_status", "status", "current_status", "state"]
)

lp_line_status_recorded_at_col = first_existing_col_line(
    line_status_df, ["recorded_at", "updated_at", "created_at", "status_at", "checked_at"]
)

lp_utilization_col = first_existing_col_line(
    line_status_df,
    [
        "utilization_rate",
        "line_utilization_rate",
        "current_utilization_rate",
        "current_utilization",
        "utilization",
    ],
)

lp_throughput_rate_col = first_existing_col_line(
    line_status_df,
    [
        "throughput_rate",
        "current_throughput_rate",
        "line_throughput_rate",
        "actual_throughput_rate",
    ],
)

lp_current_throughput_col = first_existing_col_line(
    line_status_df,
    [
        "current_throughput",
        "actual_throughput",
        "current_throughput_per_hour",
        "actual_throughput_per_hour",
        "throughput_per_hour",
    ],
)

lp_queue_wait_hours_col = first_existing_col_line(
    line_status_df,
    [
        "queue_wait_hours",
        "waiting_time_hours",
        "line_waiting_hours",
        "wait_hours",
        "queue_hours",
    ],
)

lp_queue_wait_minutes_col = first_existing_col_line(
    line_status_df,
    [
        "queue_wait_minutes",
        "waiting_time_minutes",
        "line_waiting_minutes",
        "wait_minutes",
        "queue_minutes",
    ],
)

lp_setup_hours_col = first_existing_col_line(
    line_status_df,
    [
        "setup_time_hours",
        "current_setup_time_hours",
        "setup_hours",
        "actual_setup_hours",
    ],
)

lp_setup_minutes_col = first_existing_col_line(
    line_status_df,
    [
        "setup_time_minutes",
        "current_setup_time_minutes",
        "setup_minutes",
        "actual_setup_minutes",
    ],
)

lp_changeover_hours_col = first_existing_col_line(
    line_status_df,
    [
        "changeover_time_hours",
        "current_changeover_time_hours",
        "changeover_hours",
        "actual_changeover_hours",
    ],
)

lp_changeover_minutes_col = first_existing_col_line(
    line_status_df,
    [
        "changeover_time_minutes",
        "current_changeover_time_minutes",
        "changeover_minutes",
        "actual_changeover_minutes",
    ],
)

# standard values: product_line_capability → line → product 순서로 찾음
lp_standard_throughput_col = first_existing_col_line(
    product_line_capability_df,
    [
        "standard_throughput",
        "standard_throughput_per_hour",
        "throughput_per_hour",
        "capacity_per_hour",
    ],
) or first_existing_col_line(
    line_df,
    [
        "standard_throughput",
        "standard_throughput_per_hour",
        "throughput_per_hour",
        "capacity_per_hour",
        "hourly_capacity",
    ],
)

lp_standard_setup_hours_col = (
    first_existing_col_line(
        product_line_capability_df,
        [
            "standard_setup_time_hours",
            "setup_time_hours",
            "standard_setup_hours",
        ],
    )
    or first_existing_col_line(
        line_df,
        [
            "standard_setup_time_hours",
            "setup_time_hours",
            "standard_setup_hours",
        ],
    )
    or first_existing_col_line(
        product_df,
        [
            "standard_setup_time_hours",
            "setup_time_hours",
            "standard_setup_hours",
        ],
    )
)

lp_standard_setup_minutes_col = (
    first_existing_col_line(
        product_line_capability_df,
        [
            "standard_setup_time_minutes",
            "setup_time_minutes",
            "standard_setup_minutes",
        ],
    )
    or first_existing_col_line(
        line_df,
        [
            "standard_setup_time_minutes",
            "setup_time_minutes",
            "standard_setup_minutes",
        ],
    )
    or first_existing_col_line(
        product_df,
        [
            "standard_setup_time_minutes",
            "setup_time_minutes",
            "standard_setup_minutes",
        ],
    )
)

lp_standard_changeover_hours_col = (
    first_existing_col_line(
        product_line_capability_df,
        [
            "standard_changeover_time_hours",
            "changeover_time_hours",
            "standard_changeover_hours",
        ],
    )
    or first_existing_col_line(
        line_df,
        [
            "standard_changeover_time_hours",
            "changeover_time_hours",
            "standard_changeover_hours",
        ],
    )
    or first_existing_col_line(
        product_df,
        [
            "standard_changeover_time_hours",
            "changeover_time_hours",
            "standard_changeover_hours",
        ],
    )
)

lp_standard_changeover_minutes_col = (
    first_existing_col_line(
        product_line_capability_df,
        [
            "standard_changeover_time_minutes",
            "changeover_time_minutes",
            "standard_changeover_minutes",
        ],
    )
    or first_existing_col_line(
        line_df,
        [
            "standard_changeover_time_minutes",
            "changeover_time_minutes",
            "standard_changeover_minutes",
        ],
    )
    or first_existing_col_line(
        product_df,
        [
            "standard_changeover_time_minutes",
            "changeover_time_minutes",
            "standard_changeover_minutes",
        ],
    )
)

# same_line_plans 컬럼
slp_plan_id_col = first_existing_col_line(same_line_plans_df, ["plan_id", "id"])

slp_product_id_col = first_existing_col_line(same_line_plans_df, ["product_id"])

slp_start_col = first_existing_col_line(
    same_line_plans_df,
    ["planned_start_at", "scheduled_start_at", "start_at", "production_start_at"],
)

slp_end_col = first_existing_col_line(
    same_line_plans_df, ["planned_end_at", "scheduled_end_at", "end_at", "production_end_at"]
)

line_process_mapping_result = {
    "lp_plan_id_col": lp_plan_id_col,
    "lp_plan_line_id_col": lp_plan_line_id_col,
    "lp_plan_product_id_col": lp_plan_product_id_col,
    "lp_plan_start_col": lp_plan_start_col,
    "lp_plan_end_col": lp_plan_end_col,
    "lp_plan_qty_col": lp_plan_qty_col,
    "lp_line_status_col": lp_line_status_col,
    "lp_line_status_recorded_at_col": lp_line_status_recorded_at_col,
    "lp_utilization_col": lp_utilization_col,
    "lp_throughput_rate_col": lp_throughput_rate_col,
    "lp_current_throughput_col": lp_current_throughput_col,
    "lp_queue_wait_hours_col": lp_queue_wait_hours_col,
    "lp_queue_wait_minutes_col": lp_queue_wait_minutes_col,
    "lp_setup_hours_col": lp_setup_hours_col,
    "lp_setup_minutes_col": lp_setup_minutes_col,
    "lp_changeover_hours_col": lp_changeover_hours_col,
    "lp_changeover_minutes_col": lp_changeover_minutes_col,
    "lp_standard_throughput_col": lp_standard_throughput_col,
    "lp_standard_setup_hours_col": lp_standard_setup_hours_col,
    "lp_standard_setup_minutes_col": lp_standard_setup_minutes_col,
    "lp_standard_changeover_hours_col": lp_standard_changeover_hours_col,
    "lp_standard_changeover_minutes_col": lp_standard_changeover_minutes_col,
    "slp_plan_id_col": slp_plan_id_col,
    "slp_product_id_col": slp_product_id_col,
    "slp_start_col": slp_start_col,
    "slp_end_col": slp_end_col,
}

print("Line & Process Analyzer 컬럼 매핑 결과")
line_process_mapping_result

Line & Process Analyzer 컬럼 매핑 결과

{'lp_plan_id_col': 'plan_id',
 'lp_plan_line_id_col': 'line_id',
 'lp_plan_product_id_col': 'product_id',
 'lp_plan_start_col': 'planned_start_at',
 'lp_plan_end_col': 'planned_end_at',
 'lp_plan_qty_col': 'planned_quantity',
 'lp_line_status_col': 'operation_status',
 'lp_line_status_recorded_at_col': 'recorded_at',
 'lp_utilization_col': 'utilization_rate',
 'lp_throughput_rate_col': 'throughput_rate',
 'lp_current_throughput_col': None,
 'lp_queue_wait_hours_col': None,
 'lp_queue_wait_minutes_col': None,
 'lp_setup_hours_col': None,
 'lp_setup_minutes_col': None,
 'lp_changeover_hours_col': None,
 'lp_changeover_minutes_col': None,
 'lp_standard_throughput_col': None,
 'lp_standard_setup_hours_col': None,
 'lp_standard_setup_minutes_col': None,
 'lp_standard_changeover_hours_col': None,
 'lp_standard_changeover_minutes_col': None,
 'slp_plan_id_col': 'plan_id',
 'slp_product_id_col': 'product_id',
 'slp_start_col': 'planned_start_at',
 'slp_end_col': 'planned_end_at'}

In [44]:
# Cell 45. Line & Process Analyzer 함수 정의 수정본
# 핵심 변경:
# - utilization_rate 단독으로는 LINE_ABNORMAL 후보를 생성하지 않습니다.
# - utilization_rate는 supporting signal로만 기록합니다.
# - 실제 LINE_ABNORMAL 후보는 대기시간 증가, 처리량 저하, SETUP/CHANGEOVER 초과,
#   라인 상태 이상, 일정 충돌 등 core signal이 있을 때만 생성합니다.


def get_standard_duration_hours(
    product_line_capability_df: pd.DataFrame,
    line_df: pd.DataFrame,
    product_df: pd.DataFrame,
    hours_col: str | None,
    minutes_col: str | None,
) -> float | None:
    """
    표준 setup/changeover 시간을 product_line_capability → line → product 순서로 가져옵니다.
    """
    sources = [
        product_line_capability_df,
        line_df,
        product_df,
    ]

    for df in sources:
        if df is None or df.empty:
            continue

        row = df.iloc[0]

        if hours_col and hours_col in df.columns:
            value = to_number_line(row.get(hours_col), default=np.nan)
            if not pd.isna(value):
                return value

        if minutes_col and minutes_col in df.columns:
            value = to_number_line(row.get(minutes_col), default=np.nan)
            if not pd.isna(value):
                return value / 60.0

    return None


def get_standard_throughput(
    product_line_capability_df: pd.DataFrame,
    line_df: pd.DataFrame,
) -> float | None:
    """
    기준 처리량을 product_line_capability → line 순서로 가져옵니다.
    """
    sources = [
        product_line_capability_df,
        line_df,
    ]

    candidate_cols = [
        "standard_throughput",
        "standard_throughput_per_hour",
        "throughput_per_hour",
        "capacity_per_hour",
        "hourly_capacity",
    ]

    for df in sources:
        if df is None or df.empty:
            continue

        row = df.iloc[0]

        for col in candidate_cols:
            if col in df.columns:
                value = to_number_line(row.get(col), default=np.nan)
                if not pd.isna(value) and value > 0:
                    return value

        for col in [
            "max_capacity_per_day",
            "capacity_per_day",
            "daily_capacity",
            "daily_production_capacity",
            "production_capacity",
        ]:
            if col in df.columns:
                value = to_number_line(row.get(col), default=np.nan)
                if not pd.isna(value) and value > 0:
                    return value / 24.0

    return None


def build_supporting_signal(
    signal_type: str,
    evidence: str,
    metrics: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """
    원인 후보를 단독 생성하지는 않지만,
    LINE_ABNORMAL 설명을 보강하는 보조 signal입니다.
    예: 높은 가동률, 납기 위험
    """
    return {
        "signal_type": signal_type,
        "evidence": evidence,
        "metrics": metrics or {},
    }


def analyze_same_line_schedule(
    plan_df: pd.DataFrame,
    same_line_plans_df: pd.DataFrame,
) -> dict[str, Any]:
    """
    같은 라인의 주변 계획을 보고 선행 작업 지연 또는 일정 충돌을 판단합니다.
    """
    result = {
        "signals": [],
        "analysis_note": [],
        "data_quality_notes": [],
    }

    if plan_df.empty:
        result["data_quality_notes"].append(
            "대상 production plan 데이터가 없어 생산 순서 제약 판단이 제한됩니다."
        )
        return result

    if same_line_plans_df is None or same_line_plans_df.empty:
        result["analysis_note"].append(
            "같은 라인 주변 생산계획 데이터가 없어 선행/후행 작업 영향 판단을 생략했습니다."
        )
        return result

    if not lp_plan_id_col or not slp_plan_id_col:
        result["data_quality_notes"].append("plan_id 컬럼을 찾지 못해 대상 계획 식별이 제한됩니다.")
        return result

    if not lp_plan_start_col or not lp_plan_end_col or not slp_start_col or not slp_end_col:
        result["data_quality_notes"].append(
            "계획 시작/종료 시각 컬럼을 찾지 못해 일정 충돌 판단이 제한됩니다."
        )
        return result

    target_row = plan_df.iloc[0]
    target_plan_id = target_row.get(lp_plan_id_col)
    target_start = to_datetime_line(target_row.get(lp_plan_start_col))
    target_end = to_datetime_line(target_row.get(lp_plan_end_col))

    if target_plan_id is None or target_start is None or target_end is None:
        result["data_quality_notes"].append(
            "대상 계획의 plan_id 또는 시작/종료 시각이 없어 일정 판단이 제한됩니다."
        )
        return result

    df = same_line_plans_df.copy()
    df["_start_dt"] = pd.to_datetime(df[slp_start_col], utc=True, errors="coerce")
    df["_end_dt"] = pd.to_datetime(df[slp_end_col], utc=True, errors="coerce")

    df = df.dropna(subset=["_start_dt", "_end_dt"])
    df = df.sort_values("_start_dt").reset_index(drop=True)

    if df.empty:
        result["analysis_note"].append(
            "같은 라인 생산계획은 있으나 유효한 시작/종료 시각이 없습니다."
        )
        return result

    other_df = df[df[slp_plan_id_col] != target_plan_id].copy()

    # 1. 선행 작업 종료가 대상 작업 시작보다 늦는 경우
    previous_candidates = other_df[other_df["_start_dt"] <= target_start].copy()

    if not previous_candidates.empty:
        previous_candidates = previous_candidates.sort_values("_end_dt", ascending=False)
        previous_row = previous_candidates.iloc[0]

        previous_end = previous_row["_end_dt"]
        previous_plan_id = previous_row.get(slp_plan_id_col)

        previous_delay_hours = (previous_end - target_start).total_seconds() / 3600.0

        if previous_delay_hours > 0:
            result["signals"].append(
                build_line_signal(
                    signal_type="PREVIOUS_PLAN_DELAY",
                    priority_band="TIME_CRITICAL",
                    severity=severity_by_threshold(
                        previous_delay_hours,
                        LINE_CONFIG.waiting_medium_hours,
                        LINE_CONFIG.waiting_high_hours,
                        higher_is_worse=True,
                    ),
                    delay_contribution_hours=previous_delay_hours,
                    rank_reason=(
                        "선행 작업 종료 예정 시각이 대상 작업 시작 시각보다 늦어 "
                        "생산 시작이 밀릴 수 있습니다."
                    ),
                    evidence=(
                        f"선행 계획 {previous_plan_id}의 종료 예정 시각이 대상 계획 시작 시각보다 "
                        f"약 {previous_delay_hours:.1f}시간 늦습니다."
                    ),
                    metrics={
                        "previous_plan_id": previous_plan_id,
                        "previous_end_at": str(previous_end),
                        "target_start_at": str(target_start),
                        "previous_delay_hours": previous_delay_hours,
                    },
                )
            )

    # 2. 같은 라인의 일정 충돌
    overlapping_df = other_df[
        (other_df["_start_dt"] < target_end) & (other_df["_end_dt"] > target_start)
    ].copy()

    if not overlapping_df.empty:
        overlap_plan_ids = overlapping_df[slp_plan_id_col].dropna().tolist()

        result["signals"].append(
            build_line_signal(
                signal_type="SCHEDULE_CONFLICT",
                priority_band="TIME_CRITICAL",
                severity="HIGH",
                delay_contribution_hours=None,
                rank_reason=(
                    "같은 라인에 대상 생산계획과 시간대가 겹치는 계획이 있어 "
                    "생산 순서 충돌 가능성이 있습니다."
                ),
                evidence=(
                    "같은 라인에 대상 계획과 시간대가 겹치는 생산계획이 "
                    f"{len(overlapping_df)}건 있습니다: "
                    f"{overlap_plan_ids}"
                ),
                metrics={
                    "overlap_plan_count": len(overlapping_df),
                    "overlap_plan_ids": overlap_plan_ids,
                },
            )
        )

    if not result["signals"]:
        result["analysis_note"].append(
            "같은 라인 주변 생산계획 기준 선행 작업 지연 또는 일정 충돌은 확인되지 않았습니다."
        )

    return result


def run_line_process_analyzer(risk_context: dict[str, Any]) -> dict[str, Any]:
    plan_df = risk_context["tables"]["plan"].copy()
    line_df = risk_context["tables"]["line"].copy()
    line_status_df = risk_context["tables"]["line_status"].copy()
    product_df = risk_context["tables"]["product"].copy()

    product_line_capability_df = (
        risk_context["tables"].get("product_line_capability", pd.DataFrame()).copy()
    )

    same_line_plans_df = risk_context["tables"].get("same_line_plans", pd.DataFrame()).copy()

    line_id = risk_context["ids"].get("line_id")
    agent_input = risk_context.get("agent_input", {})

    signals = []
    supporting_signals = []
    data_quality_notes = []
    analysis_note = []

    line_status_row = None

    if line_status_df is not None and not line_status_df.empty:
        line_status_row = line_status_df.iloc[0]
    else:
        data_quality_notes.append("line_status 데이터가 없어 라인 현재 상태 판단이 제한됩니다.")

    # 1. 라인 operation_status 판단
    operation_status = None

    if line_status_row is not None and lp_line_status_col:
        operation_status = normalize_status_line(line_status_row.get(lp_line_status_col))

        if operation_status in LINE_CONFIG.blocker_statuses:
            signals.append(
                build_line_signal(
                    signal_type="LINE_OPERATION_STATUS",
                    priority_band="BLOCKER",
                    severity="HIGH",
                    delay_contribution_hours=None,
                    rank_reason="라인 상태가 생산 진행을 직접 제한하는 상태입니다.",
                    evidence=f"배정 라인 {line_id}의 현재 상태가 {operation_status}입니다.",
                    metrics={
                        "line_id": line_id,
                        "operation_status": operation_status,
                    },
                )
            )

        elif operation_status in LINE_CONFIG.flow_delay_statuses:
            signals.append(
                build_line_signal(
                    signal_type="LINE_OPERATION_STATUS",
                    priority_band="FLOW_DELAY",
                    severity="MEDIUM",
                    delay_contribution_hours=None,
                    rank_reason="라인 상태가 생산 흐름 지연 가능성을 나타냅니다.",
                    evidence=f"배정 라인 {line_id}의 현재 상태가 {operation_status}입니다.",
                    metrics={
                        "line_id": line_id,
                        "operation_status": operation_status,
                    },
                )
            )

        elif operation_status in LINE_CONFIG.normal_statuses:
            pass

        else:
            if operation_status is not None:
                data_quality_notes.append(
                    f"정상/비정상 규칙에 포함되지 않은 라인 상태가 있습니다: {operation_status}"
                )

    elif line_status_row is not None and not lp_line_status_col:
        data_quality_notes.append("line_status에서 operation_status 계열 컬럼을 찾지 못했습니다.")

    # 2. 라인 가동률 판단
    # 중요: utilization_rate는 단독 원인 signal로 생성하지 않습니다.
    # 높은 가동률은 supporting signal로만 기록합니다.
    utilization_rate = None
    high_utilization_detected = False

    if line_status_row is not None and lp_utilization_col:
        utilization_rate = normalize_ratio_line(line_status_row.get(lp_utilization_col))

        if (
            utilization_rate is not None
            and utilization_rate >= LINE_CONFIG.utilization_medium_threshold
        ):
            high_utilization_detected = True

            severity = severity_by_threshold(
                utilization_rate,
                LINE_CONFIG.utilization_medium_threshold,
                LINE_CONFIG.utilization_high_threshold,
                higher_is_worse=True,
            )

            supporting_signals.append(
                build_supporting_signal(
                    signal_type="HIGH_UTILIZATION_SUPPORT",
                    evidence=(
                        f"배정 라인 {line_id}의 현재 가동률은 "
                        f"{format_ratio_line(utilization_rate)}입니다. "
                        f"다만 가동률 상승만으로는 LINE_ABNORMAL 원인으로 판단하지 않고, "
                        "대기시간 증가·처리량 저하·SETUP 지연 등과 함께 해석합니다."
                    ),
                    metrics={
                        "line_id": line_id,
                        "utilization_rate": utilization_rate,
                        "severity": severity,
                        "threshold": LINE_CONFIG.utilization_medium_threshold,
                    },
                )
            )

    # 3. 처리량 저하 판단
    throughput_rate = None
    current_throughput = None
    standard_throughput = get_standard_throughput(product_line_capability_df, line_df)

    if line_status_row is not None and lp_throughput_rate_col:
        throughput_rate = normalize_ratio_line(line_status_row.get(lp_throughput_rate_col))

    if line_status_row is not None and lp_current_throughput_col:
        current_throughput = to_number_line(
            line_status_row.get(lp_current_throughput_col), default=np.nan
        )

        if pd.isna(current_throughput):
            current_throughput = None

    if (
        throughput_rate is None
        and current_throughput is not None
        and standard_throughput is not None
        and standard_throughput > 0
    ):
        throughput_rate = current_throughput / standard_throughput

    if throughput_rate is not None and throughput_rate < LINE_CONFIG.throughput_medium_threshold:
        severity = severity_by_threshold(
            throughput_rate,
            LINE_CONFIG.throughput_medium_threshold,
            LINE_CONFIG.throughput_high_threshold,
            higher_is_worse=False,
        )

        delay_hours = None
        planned_qty = None

        if not plan_df.empty and lp_plan_qty_col:
            planned_qty = to_number_line(plan_df.iloc[0].get(lp_plan_qty_col), default=np.nan)

            if pd.isna(planned_qty):
                planned_qty = None

        if (
            planned_qty is not None
            and current_throughput is not None
            and standard_throughput is not None
        ):
            if current_throughput > 0 and standard_throughput > 0:
                delay_hours = max(
                    planned_qty / current_throughput - planned_qty / standard_throughput,
                    0.0,
                )

        signals.append(
            build_line_signal(
                signal_type="THROUGHPUT_LOW",
                priority_band="FLOW_DELAY",
                severity=severity,
                delay_contribution_hours=delay_hours,
                rank_reason=(
                    "현재 라인 처리량이 기준보다 낮아 생산 완료 시점이 지연될 가능성이 있습니다."
                ),
                evidence=(
                    f"배정 라인 {line_id}의 처리량 비율은 {format_ratio_line(throughput_rate)}로 "
                    "기준 "
                    f"{format_ratio_line(LINE_CONFIG.throughput_medium_threshold)}보다 "
                    "낮습니다."
                ),
                metrics={
                    "line_id": line_id,
                    "throughput_rate": throughput_rate,
                    "current_throughput": current_throughput,
                    "standard_throughput": standard_throughput,
                    "planned_qty": planned_qty,
                    "delay_hours": delay_hours,
                },
            )
        )

    # 4. 대기시간 증가 판단
    waiting_hours = None

    if line_status_row is not None:
        waiting_hours = get_duration_hours_from_row(
            line_status_row,
            hours_cols=[lp_queue_wait_hours_col] if lp_queue_wait_hours_col else [],
            minutes_cols=[lp_queue_wait_minutes_col] if lp_queue_wait_minutes_col else [],
        )

        if waiting_hours is not None and waiting_hours >= LINE_CONFIG.waiting_medium_hours:
            severity = severity_by_threshold(
                waiting_hours,
                LINE_CONFIG.waiting_medium_hours,
                LINE_CONFIG.waiting_high_hours,
                higher_is_worse=True,
            )

            signals.append(
                build_line_signal(
                    signal_type="WAITING_TIME_HIGH",
                    priority_band="FLOW_DELAY",
                    severity=severity,
                    delay_contribution_hours=waiting_hours,
                    rank_reason=(
                        "라인 대기시간이 기준보다 길어 생산 시작 또는 흐름 지연 가능성이 있습니다."
                    ),
                    evidence=(
                        f"배정 라인 {line_id}의 대기시간은 {format_hours_line(waiting_hours)}로 "
                        f"기준 {format_hours_line(LINE_CONFIG.waiting_medium_hours)}를 초과합니다."
                    ),
                    metrics={
                        "line_id": line_id,
                        "waiting_hours": waiting_hours,
                        "threshold": LINE_CONFIG.waiting_medium_hours,
                    },
                )
            )

    # 5. SETUP 시간 증가 판단
    setup_hours = None
    standard_setup_hours = None

    if line_status_row is not None:
        setup_hours = get_duration_hours_from_row(
            line_status_row,
            hours_cols=[lp_setup_hours_col] if lp_setup_hours_col else [],
            minutes_cols=[lp_setup_minutes_col] if lp_setup_minutes_col else [],
        )

    standard_setup_hours = get_standard_duration_hours(
        product_line_capability_df=product_line_capability_df,
        line_df=line_df,
        product_df=product_df,
        hours_col=lp_standard_setup_hours_col,
        minutes_col=lp_standard_setup_minutes_col,
    )

    setup_overrun_hours = None

    if setup_hours is not None and standard_setup_hours is not None:
        setup_overrun_hours = setup_hours - standard_setup_hours

        if setup_overrun_hours >= LINE_CONFIG.setup_overrun_medium_hours:
            severity = severity_by_threshold(
                setup_overrun_hours,
                LINE_CONFIG.setup_overrun_medium_hours,
                LINE_CONFIG.setup_overrun_high_hours,
                higher_is_worse=True,
            )

            signals.append(
                build_line_signal(
                    signal_type="SETUP_TIME_OVERRUN",
                    priority_band="FLOW_DELAY",
                    severity=severity,
                    delay_contribution_hours=setup_overrun_hours,
                    rank_reason="SETUP 시간이 표준보다 길어 생산 시작 시점이 지연될 수 있습니다.",
                    evidence=(
                        f"SETUP 시간은 {format_hours_line(setup_hours)}이고 "
                        f"표준 SETUP 시간은 {format_hours_line(standard_setup_hours)}로, "
                        f"초과 시간은 {format_hours_line(setup_overrun_hours)}입니다."
                    ),
                    metrics={
                        "line_id": line_id,
                        "setup_hours": setup_hours,
                        "standard_setup_hours": standard_setup_hours,
                        "setup_overrun_hours": setup_overrun_hours,
                    },
                )
            )

    if operation_status in {"SETUP"} and setup_hours is None:
        data_quality_notes.append(
            "라인 상태가 SETUP이나 setup_time 컬럼을 찾지 못해 SETUP 지연 시간 계산이 제한됩니다."
        )

    # 6. CHANGEOVER 시간 증가 판단
    changeover_hours = None
    standard_changeover_hours = None

    if line_status_row is not None:
        changeover_hours = get_duration_hours_from_row(
            line_status_row,
            hours_cols=[lp_changeover_hours_col] if lp_changeover_hours_col else [],
            minutes_cols=[lp_changeover_minutes_col] if lp_changeover_minutes_col else [],
        )

    standard_changeover_hours = get_standard_duration_hours(
        product_line_capability_df=product_line_capability_df,
        line_df=line_df,
        product_df=product_df,
        hours_col=lp_standard_changeover_hours_col,
        minutes_col=lp_standard_changeover_minutes_col,
    )

    changeover_overrun_hours = None

    if changeover_hours is not None and standard_changeover_hours is not None:
        changeover_overrun_hours = changeover_hours - standard_changeover_hours

        if changeover_overrun_hours >= LINE_CONFIG.changeover_overrun_medium_hours:
            severity = severity_by_threshold(
                changeover_overrun_hours,
                LINE_CONFIG.changeover_overrun_medium_hours,
                LINE_CONFIG.changeover_overrun_high_hours,
                higher_is_worse=True,
            )

            signals.append(
                build_line_signal(
                    signal_type="CHANGEOVER_TIME_OVERRUN",
                    priority_band="FLOW_DELAY",
                    severity=severity,
                    delay_contribution_hours=changeover_overrun_hours,
                    rank_reason="제품 전환 시간이 표준보다 길어 생산 흐름이 지연될 수 있습니다.",
                    evidence=(
                        f"제품 전환 시간은 {format_hours_line(changeover_hours)}이고 "
                        f"표준 전환 시간은 {format_hours_line(standard_changeover_hours)}로, "
                        f"초과 시간은 {format_hours_line(changeover_overrun_hours)}입니다."
                    ),
                    metrics={
                        "line_id": line_id,
                        "changeover_hours": changeover_hours,
                        "standard_changeover_hours": standard_changeover_hours,
                        "changeover_overrun_hours": changeover_overrun_hours,
                    },
                )
            )

    if operation_status in {"CHANGEOVER"} and changeover_hours is None:
        data_quality_notes.append(
            "라인 상태가 CHANGEOVER이나 changeover_time 컬럼을 찾지 못해 "
            "제품 전환 지연 시간 계산이 제한됩니다."
        )

    # 7. 같은 라인 생산계획 기반 선행 작업 / 일정 충돌 판단
    schedule_result = analyze_same_line_schedule(
        plan_df=plan_df,
        same_line_plans_df=same_line_plans_df,
    )

    signals.extend(schedule_result["signals"])
    data_quality_notes.extend(schedule_result["data_quality_notes"])
    analysis_note.extend(schedule_result["analysis_note"])

    # 8. 납기 위험은 supporting signal로만 사용
    risk_level = str(agent_input.get("risk_level", "")).upper()
    predicted_delay_days = to_number_line(
        agent_input.get("predicted_delay_days"),
        default=np.nan,
    )

    if risk_level and risk_level != "SAFE":
        supporting_signals.append(
            build_supporting_signal(
                signal_type="DUE_RISK_SUPPORT",
                evidence=(
                    f"해당 주문은 위험 등급 {risk_level}이며, "
                    f"예상 지연 일수는 {predicted_delay_days:.2f}일입니다."
                    if not pd.isna(predicted_delay_days)
                    else f"해당 주문은 위험 등급 {risk_level}입니다."
                ),
                metrics={
                    "risk_level": risk_level,
                    "predicted_delay_days": None
                    if pd.isna(predicted_delay_days)
                    else predicted_delay_days,
                },
            )
        )

    detail = {
        "line_id": line_id,
        "operation_status": operation_status,
        "utilization_rate": utilization_rate,
        "high_utilization_detected": high_utilization_detected,
        "throughput_rate": throughput_rate,
        "current_throughput": current_throughput,
        "standard_throughput": standard_throughput,
        "waiting_hours": waiting_hours,
        "setup_hours": setup_hours,
        "standard_setup_hours": standard_setup_hours,
        "setup_overrun_hours": setup_overrun_hours,
        "changeover_hours": changeover_hours,
        "standard_changeover_hours": standard_changeover_hours,
        "changeover_overrun_hours": changeover_overrun_hours,
        "core_signal_count": len(signals),
        "supporting_signal_count": len(supporting_signals),
    }

    cause_candidates = []

    # 핵심: core signal이 있을 때만 LINE_ABNORMAL 후보 생성
    if signals:
        priority_band = min_priority_band([s["priority_band"] for s in signals])
        severity = max_severity([s["severity"] for s in signals])

        delay_values = [
            s["delay_contribution_hours"]
            for s in signals
            if s.get("delay_contribution_hours") is not None
        ]

        delay_contribution_hours = max(delay_values) if delay_values else None

        top_signal = sorted(
            signals,
            key=lambda s: (
                {
                    "BLOCKER": 1,
                    "TIME_CRITICAL": 2,
                    "FLOW_DELAY": 3,
                    "CONTRIBUTOR": 4,
                }.get(s["priority_band"], 99),
                {
                    "HIGH": 1,
                    "MEDIUM": 2,
                    "LOW": 3,
                    "UNKNOWN": 4,
                }.get(s["severity"], 99),
            ),
        )[0]

        evidence = [s["evidence"] for s in signals]

        # supporting evidence는 뒤에 추가
        for support in supporting_signals:
            evidence.append(support["evidence"])

        cause_candidates.append(
            {
                "cause_type": "LINE_ABNORMAL",
                "korean_name": "라인 상태 이상",
                "priority_band": priority_band,
                "severity": severity,
                "delay_contribution_hours": delay_contribution_hours,
                "rank_reason": top_signal["rank_reason"],
                "evidence": evidence,
                "metrics": {
                    **detail,
                    "signals": signals,
                    "supporting_signals": supporting_signals,
                },
                "action_hint": (
                    "대체 라인 배정, 생산 순서 조정, SETUP/전환 시간 단축, "
                    "라인 부하 완화 가능 여부를 검토합니다."
                ),
            }
        )

    else:
        if high_utilization_detected:
            analysis_note.append(
                "라인 가동률은 높지만 대기시간 증가, 처리량 저하, "
                "SETUP/전환 지연, 일정 충돌이 함께 확인되지 않아 "
                "정상적인 고가동 상태로 판단했습니다."
            )
        elif not data_quality_notes:
            analysis_note.append(
                "배정 라인의 상태, 처리량, 대기시간, SETUP/전환 시간, "
                "주변 생산계획 기준에서 LINE_ABNORMAL 후보를 생성하지 않았습니다."
            )

    return {
        "analyzer": "LineProcessAnalyzer",
        "status": "COMPLETED",
        "cause_candidates": cause_candidates,
        "detail": detail,
        "signals": signals,
        "supporting_signals": supporting_signals,
        "analysis_note": analysis_note,
        "data_quality": {
            "status": "OK" if not data_quality_notes else "PARTIAL",
            "notes": data_quality_notes,
        },
        "column_mapping": line_process_mapping_result,
    }


print("Line & Process Analyzer 함수 정의 완료")

Line & Process Analyzer 함수 정의 완료

In [45]:
# Cell 46. Line & Process Analyzer 실행 수정본

line_process_analysis = run_line_process_analyzer(risk_context)

print("Line & Process Analyzer status:", line_process_analysis["status"])
print("Data quality:", line_process_analysis["data_quality"])

print("\nAnalysis note:")
for note in line_process_analysis.get("analysis_note", []):
    print("-", note)

print("\n라인/공정 상세 계산 결과")
display(pd.DataFrame([line_process_analysis["detail"]]))

print("\nCore line abnormal signals")
signals_df = pd.DataFrame(line_process_analysis["signals"])
display(signals_df)

print("\nSupporting signals")
supporting_signals_df = pd.DataFrame(line_process_analysis["supporting_signals"])
display(supporting_signals_df)

print("\n원인 후보 수:", len(line_process_analysis["cause_candidates"]))

if line_process_analysis["cause_candidates"]:
    for idx, candidate in enumerate(line_process_analysis["cause_candidates"], start=1):
        print("\n" + "-" * 100)
        print(f"[Candidate {idx}] {candidate['cause_type']} / {candidate['korean_name']}")
        print("priority_band:", candidate["priority_band"])
        print("severity:", candidate["severity"])
        print("delay_contribution_hours:", candidate["delay_contribution_hours"])
        print("rank_reason:", candidate["rank_reason"])
        print("evidence:")
        for ev in candidate["evidence"]:
            print("-", ev)
else:
    print("Line & Process 관련 원인 후보가 없습니다.")

Line & Process Analyzer status: COMPLETED
Data quality: {'status': 'OK', 'notes': []}

Analysis note:
- 같은 라인 주변 생산계획 기준 선행 작업 지연 또는 일정 충돌은 확인되지 않았습니다.

라인/공정 상세 계산 결과

,line_id,operation_status,utilization_rate,high_utilization_detected,throughput_rate,current_throughput,standard_throughput,waiting_hours,setup_hours,standard_setup_hours,setup_overrun_hours,changeover_hours,standard_changeover_hours,changeover_overrun_hours,core_signal_count,supporting_signal_count
0,2,RUNNING,0.81,False,0.79,None,520.833333,None,None,None,None,None,None,None,1,1

Core line abnormal signals

,signal_type,priority_band,severity,evidence,rank_reason,delay_contribution_hours,metrics
0,THROUGHPUT_LOW,FLOW_DELAY,MEDIUM,배정 라인 2의 처리량 비율은 79.0%로 기준 90.0%보다 낮습니다.,현재 라인 처리량이 기준보다 낮아 생산 완료 시점이 지연될 가능성이 있습니다.,None,"{'line_id': 2, 'throughput_rate': 0.79, 'current_throughput': None, 'standard_throughput': 520.8333333333334, 'plann..."

Supporting signals

,signal_type,evidence,metrics
0,DUE_RISK_SUPPORT,"해당 주문은 위험 등급 WARNING이며, 예상 지연 일수는 1.98일입니다.","{'risk_level': 'WARNING', 'predicted_delay_days': 1.98}"

원인 후보 수: 1

----------------------------------------------------------------------------------------------------
[Candidate 1] LINE_ABNORMAL / 라인 상태 이상
priority_band: FLOW_DELAY
severity: MEDIUM
delay_contribution_hours: None
rank_reason: 현재 라인 처리량이 기준보다 낮아 생산 완료 시점이 지연될 가능성이 있습니다.
evidence:
- 배정 라인 2의 처리량 비율은 79.0%로 기준 90.0%보다 낮습니다.
- 해당 주문은 위험 등급 WARNING이며, 예상 지연 일수는 1.98일입니다.

In [46]:
# Cell 47. Line & Process Analyzer 결과 저장 수정본

if "analyzer_results" not in risk_context:
    risk_context["analyzer_results"] = {}

risk_context["analyzer_results"]["line_process"] = {
    "analyzer": line_process_analysis["analyzer"],
    "status": line_process_analysis["status"],
    "cause_candidates": line_process_analysis["cause_candidates"],
    "signals": line_process_analysis["signals"],
    "supporting_signals": line_process_analysis["supporting_signals"],
    "analysis_note": line_process_analysis.get("analysis_note", []),
    "data_quality": line_process_analysis["data_quality"],
}

line_process_analysis_for_next_node = risk_context["analyzer_results"]["line_process"]

print(
    json.dumps(
        line_process_analysis_for_next_node,
        ensure_ascii=False,
        indent=2,
        default=str,
    )
)

{
  "analyzer": "LineProcessAnalyzer",
  "status": "COMPLETED",
  "cause_candidates": [
    {
      "cause_type": "LINE_ABNORMAL",
      "korean_name": "라인 상태 이상",
      "priority_band": "FLOW_DELAY",
      "severity": "MEDIUM",
      "delay_contribution_hours": null,
      "rank_reason": "현재 라인 처리량이 기준보다 낮아 생산 완료 시점이 지연될 가능성이 있습니다.",
      "evidence": [
        "배정 라인 2의 처리량 비율은 79.0%로 기준 90.0%보다 낮습니다.",
        "해당 주문은 위험 등급 WARNING이며, 예상 지연 일수는 1.98일입니다."
      ],
      "metrics": {
        "line_id": 2,
        "operation_status": "RUNNING",
        "utilization_rate": 0.81,
        "high_utilization_detected": false,
        "throughput_rate": 0.79,
        "current_throughput": null,
        "standard_throughput": 520.8333333333334,
        "waiting_hours": null,
        "setup_hours": null,
        "standard_setup_hours": null,
        "setup_overrun_hours": null,
        "changeover_hours": null,
        "standard_changeover_hours": null,
        "changeover_overrun_hours": null,
        "core_signal_count": 1,
        "supporting_signal_count": 1,
        "signals": [
          {
            "signal_type": "THROUGHPUT_LOW",
            "priority_band": "FLOW_DELAY",
            "severity": "MEDIUM",
            "evidence": "배정 라인 2의 처리량 비율은 79.0%로 기준 90.0%보다 낮습니다.",
            "rank_reason": "현재 라인 처리량이 기준보다 낮아 생산 완료 시점이 지연될 가능성이 있습니다.",
            "delay_contribution_hours": null,
            "metrics": {
              "line_id": 2,
              "throughput_rate": 0.79,
              "current_throughput": null,
              "standard_throughput": 520.8333333333334,
              "planned_qty": 12800.0,
              "delay_hours": null
            }
          }
        ],
        "supporting_signals": [
          {
            "signal_type": "DUE_RISK_SUPPORT",
            "evidence": "해당 주문은 위험 등급 WARNING이며, 예상 지연 일수는 1.98일입니다.",
            "metrics": {
              "risk_level": "WARNING",
              "predicted_delay_days": 1.98
            }
          }
        ]
      },
      "action_hint": "대체 라인 배정, 생산 순서 조정, SETUP/전환 시간 단축, 라인 부하 완화 가능 여부를 검토합니다."
    }
  ],
  "signals": [
    {
      "signal_type": "THROUGHPUT_LOW",
      "priority_band": "FLOW_DELAY",
      "severity": "MEDIUM",
      "evidence": "배정 라인 2의 처리량 비율은 79.0%로 기준 90.0%보다 낮습니다.",
      "rank_reason": "현재 라인 처리량이 기준보다 낮아 생산 완료 시점이 지연될 가능성이 있습니다.",
      "delay_contribution_hours": null,
      "metrics": {
        "line_id": 2,
        "throughput_rate": 0.79,
        "current_throughput": null,
        "standard_throughput": 520.8333333333334,
        "planned_qty": 12800.0,
        "delay_hours": null
      }
    }
  ],
  "supporting_signals": [
    {
      "signal_type": "DUE_RISK_SUPPORT",
      "evidence": "해당 주문은 위험 등급 WARNING이며, 예상 지연 일수는 1.98일입니다.",
      "metrics": {
        "risk_level": "WARNING",
        "predicted_delay_days": 1.98
      }
    }
  ],
  "analysis_note": [
    "같은 라인 주변 생산계획 기준 선행 작업 지연 또는 일정 충돌은 확인되지 않았습니다."
  ],
  "data_quality": {
    "status": "OK",
    "notes": []
  }
}